export type ComponentCategory =
  | "ticket-stub"
  | "form"
  | "pickers"
  | "charts"
  | "data"
  | "feedback"
  | "navigation"
  | "editors"
  | "media";

export type ComponentMeta = {
  name: string;
  title: string;
  description: string;
  category: ComponentCategory;
  isNew?: boolean;
};

export const categories: { id: ComponentCategory; name: string; description: string }[] = [
  { id: "ticket-stub", name: "Ticket Stub & Retro", description: "Tickets, stubs, coupons, passes, split-flap, and tactile mechanical controls." },
  { id: "form", name: "Core Form & Inputs", description: "Buttons, text inputs, checkboxes, toggles, switches, and sliders." },
  { id: "pickers", name: "Pickers & Selectors", description: "Date, color, time, country, currency, file dropzone, and complex pickers." },
  { id: "charts", name: "Charts & Visualization", description: "Bar, line, bubble, sunburst, sparkline, radar, and data visualizations." },
  { id: "data", name: "Data Display & Tables", description: "Tables, data grids, metric cards, stat tiles, accordions, and bento layouts." },
  { id: "feedback", name: "Feedback & Overlays", description: "Dialogs, sheets, alerts, toasts, callouts, and status badges." },
  { id: "navigation", name: "Navigation & Menus", description: "Tabs, breadcrumbs, steppers, menubars, pagination, command palette, and shells." },
  { id: "editors", name: "Editors & DevTools", description: "Code, markdown, diff, JSON editors, regex tester, cron builder, and console." },
  { id: "media", name: "Media & Interactive", description: "Audio players, waveforms, video frames, lightboxes, and social cards." },
];

export const components: ComponentMeta[] = [
  { name: "button", title: "Button", description: "Animated button with hover feedback and crisp focus.", category: "form" },
  { name: "input", title: "Input", description: "Text input with dashed focus border and design tokens.", category: "form" },
  { name: "textarea", title: "Textarea", description: "Multi-line text area matching Input styling.", category: "form" },
  { name: "checkbox", title: "Checkbox", description: "Crisp checkbox with bold checked states.", category: "form" },
  { name: "switch", title: "Switch", description: "Two-state toggle switch with sliding thumb.", category: "form" },
  { name: "radio-group", title: "Radio Group", description: "Accessible single-select radio button set.", category: "form" },
  { name: "slider", title: "Slider", description: "Draggable value slider with chunky thumb.", category: "form" },
  { name: "select", title: "Select", description: "Custom dashed listbox dropdown with keyboard navigation.", category: "pickers" },
  { name: "stepper", title: "Stepper", description: "Increment and decrement buttons with mono readout.", category: "form" },
  { name: "pin-input", title: "Pin Input", description: "Segmented single-character boxes for codes and OTP.", category: "pickers" },
  { name: "rating", title: "Rating", description: "Interactive star rating with live hover preview.", category: "form" },
  { name: "copy-button", title: "Copy Button", description: "Tactile button with clipboard feedback and check state.", category: "form" },
  { name: "search-bar", title: "Search Bar", description: "Dashed search field with shortcut keycap and clear action.", category: "form" },
  { name: "combobox", title: "Combobox", description: "Filterable searchable dropdown with instant keyboard filter.", category: "pickers" },
  { name: "file-dropzone", title: "File Dropzone", description: "Drag-and-drop upload zone with dashed borders and file preview.", category: "pickers" },
  { name: "color-picker", title: "Color Picker", description: "Palette swatch picker with framing and active mark.", category: "pickers" },
  { name: "password-strength", title: "Password Strength", description: "Segmented security verification meter with animated strength bars and criteria checklist.", category: "form" },
  { name: "inline-edit", title: "Inline Edit", description: "Click-to-edit field with focus outline, animated save pulse, and cancel action.", category: "form" },
  { name: "time-input", title: "Time Input", description: "Curtain call showtime selector with hours, minutes, and AM/PM stepper.", category: "pickers" },
  { name: "masked-input", title: "Masked Input", description: "Formatted code field with auto-formatted delimiters and validation mark.", category: "pickers" },
  { name: "date-picker", title: "Date Picker", description: "Date picker input with popover calendar and quick date selection.", category: "pickers" },
  { name: "dual-slider", title: "Dual Slider", description: "Price range selector with minimum and maximum draggable handles.", category: "form" },
  { name: "mention-input", title: "Mention Input", description: "Mention input with instant @ autocomplete popover.", category: "media" },
  { name: "autocomplete", title: "Autocomplete", description: "Typeahead search input with instant suggestions and keyboard select.", category: "pickers" },
  { name: "transfer-list", title: "Transfer List", description: "Two-column transfer list between available and claimed items.", category: "data" },
  { name: "tree-select", title: "Tree Select", description: "Hierarchical seating dropdown selector with expandable zone nodes.", category: "pickers" },
  { name: "masked-currency", title: "Masked Currency", description: "Formatted currency price input with prefix badge and numeric mask.", category: "pickers" },
  { name: "segmented-switch", title: "Segmented Switch", description: "Mechanical multi-option lever switch with smooth slide carriage.", category: "form" },
  { name: "theme-toggle", title: "Theme Toggle", description: "Theme switcher with day and night flip animation.", category: "media" },
  { name: "signature-pad", title: "Signature Pad", description: "Interactive canvas endorsement pad with clear action and receipt stamp.", category: "pickers" },
  { name: "seat-map", title: "Seat Map", description: "Interactive arena seating chart matrix grid with row letters, seat numbers, tier types, and price calculator.", category: "ticket-stub" },
  { name: "keypad", title: "Keypad", description: "Numeric PIN keypad with tactile mechanical keys, visual pulse, and masked PIN display.", category: "ticket-stub" },
  { name: "tag-input", title: "Tag Input", description: "Tag input with pill chip badges, remove buttons, backspace deletion, and dashed container.", category: "pickers" },
  { name: "ticket-card", title: "Ticket Card", description: "Complete admission ticket with notched edges and seat details.", category: "ticket-stub" },
  { name: "coupon", title: "Coupon", description: "Discount coupon with scissor cutout lines and promo code copy.", category: "ticket-stub" },
  { name: "boarding-pass", title: "Boarding Pass", description: "Flight pass with origin, destination and receipt section.", category: "ticket-stub" },
  { name: "price-tag", title: "Price Tag", description: "Price tag with eyelet string hole and sale mark.", category: "ticket-stub" },
  { name: "luggage-tag", title: "Luggage Tag", description: "Baggage claim tag with handle loop and destination code.", category: "ticket-stub" },
  { name: "barcode", title: "Barcode", description: "Dynamic SVG barcode with mono serial readout.", category: "ticket-stub" },
  { name: "stamp-seal", title: "Stamp Seal", description: "Rotated rubber stamp badge with double dashed circular ring.", category: "ticket-stub" },
  { name: "card", title: "Card", description: "Double-frame surface container with header, content, and footer.", category: "data" },
  { name: "badge", title: "Badge", description: "Micro status pill with subtle entrance transition.", category: "feedback" },
  { name: "avatar", title: "Avatar", description: "Initials or photo badge with dashed ring.", category: "data" },
  { name: "progress", title: "Progress", description: "Marching striped progress indicator bar.", category: "feedback" },
  { name: "kbd", title: "Kbd", description: "Keycap indicator with raised bottom border for shortcuts.", category: "navigation" },
  { name: "star", title: "Star", description: "Current-color star glyph for ratings and counts.", category: "data" },
  { name: "separator", title: "Separator", description: "Horizontal or vertical dashed divider.", category: "navigation" },
  { name: "table", title: "Table", description: "Data table with dashed row dividers and mono headers.", category: "data" },
  { name: "marquee", title: "Marquee", description: "Smooth ticker reel that pauses on hover.", category: "media" },
  { name: "timeline", title: "Timeline", description: "Vertical chronological events with dashed connection stem.", category: "data" },
  { name: "sparkline", title: "Sparkline", description: "Lightweight SVG trend sparkline with animated end-point.", category: "charts" },
  { name: "bar-chart", title: "Bar Chart", description: "Mini data bar chart with dashed guideline grids and hover zoom.", category: "charts" },
  { name: "calendar", title: "Calendar", description: "Month calendar with date selection, month navigation, and today indicator.", category: "pickers" },
  { name: "data-table", title: "Data Table", description: "Sortable, searchable data table with row selection and pagination.", category: "data" },
  { name: "video-frame", title: "Video Frame", description: "Cinema screening container with sprocket edges and play overlay.", category: "media" },
  { name: "audio-mini", title: "Audio Mini", description: "Compact audio player with animated equalizer bars and duration counter.", category: "media" },
  { name: "section-heading", title: "Section Heading", description: "Theater and arena section divider banner with dashed rules and zone badges.", category: "navigation" },
  { name: "lightbox", title: "Lightbox", description: "Fullscreen media viewer with film frame edges and image paging.", category: "media" },
  { name: "sticky-bar", title: "Sticky Bar", description: "Floating bottom checkout bar with item counter and admission button.", category: "navigation" },
  { name: "stack", title: "Stack", description: "Stacked container with staggered angles and hover fan-out.", category: "data" },
  { name: "container", title: "Container", description: "Centered layout wrapper with notch cutouts.", category: "data" },
  { name: "kanban-lite", title: "Kanban Lite", description: "Queue and stage progression board with notch cards.", category: "data" },
  { name: "gantt-lite", title: "Gantt Lite", description: "Interactive festival and stage timetable schedule with animated now indicator.", category: "data" },
  { name: "stopwatch", title: "Stopwatch", description: "Precision timer with lap tear-offs and digital readout.", category: "media" },
  { name: "countup", title: "Countup", description: "Mechanical turnstile odometer counter with animated tally and slot frames.", category: "media" },
  { name: "nfc-badge", title: "NFC Badge", description: "Contactless gate pass tap simulator with animated radio wave ripple pulse, status badge, lanyard notch, and admission chime.", category: "ticket-stub" },
  { name: "scratch-off", title: "Scratch Off", description: "Lottery ticket with interactive foil scratch layer and auto-reveal.", category: "ticket-stub" },
  { name: "qr-reader", title: "QR Reader", description: "Turnstile simulated camera QR and barcode scanner viewfinder with animated laser sweep and targeting reticle.", category: "ticket-stub" },
  { name: "audio-waveform", title: "Audio Waveform", description: "Interactive multi-bar audio wave visualizer for concert recordings with live animated frequency bars and timestamp readout.", category: "media" },
  { name: "ticket-fold", title: "Ticket Fold", description: "3D accordion fold pass that unfolds with smooth perspective rotation and tear-away slip.", category: "ticket-stub" },
  { name: "split-flap", title: "Split Flap", description: "Mechanical departure board with flipping characters and retro terminal styling.", category: "ticket-stub" },
  { name: "watermark", title: "Watermark", description: "Repeating watermark pattern with security angle.", category: "ticket-stub" },
  { name: "turnstile-gate", title: "Turnstile Gate", description: "Mechanical rotor barrier with pass counter, status LED, and push animation.", category: "ticket-stub" },
  { name: "collapsible", title: "Collapsible", description: "Standalone expandable disclosure card with notch header, animated height reveal and status mark.", category: "data" },
  { name: "aspect-ratio", title: "Aspect Ratio", description: "Proportional media container with preset ratios, framed border, and corner guides.", category: "data" },
  { name: "resizable", title: "Resizable", description: "Splitter layout panels with draggable resize handle, min/max limits and collapse button.", category: "navigation" },
  { name: "scroll-area", title: "Scroll Area", description: "Custom styled scrollable container with customized dashed scrollbar track, thumb indicator, horizontal/vertical support, and perforated top/bottom shadow fades.", category: "navigation" },
  { name: "pricing-table", title: "Pricing Table", description: "3-tier matrix with billing switcher, highlighted plan and feature checklist.", category: "data" },
  { name: "metric-card", title: "Metric Card", description: "Dashboard KPI card with value, trend delta and period label.", category: "data" },
  { name: "code-block", title: "Code Block", description: "Code snippet block with filename tab, language badge and copy button.", category: "editors" },
  { name: "activity-feed", title: "Activity Feed", description: "Universal user and team activity stream for deployments, invites, edits, and security audits with timeline avatars, action badges, relative timestamps, and event icons.", category: "data" },
  { name: "credit-card", title: "Credit Card", description: "Universal payment card visualizer with real-time card number formatting, brand badge detection (Visa, Mastercard, Amex), metallic EMV chip, and interactive 3D flip card to show CVV.", category: "data" },
  { name: "file-upload-list", title: "File Upload List", description: "Multi-file upload manager queue with individual file progress percentage bars, file size formatting (KB/MB), file type badges, cancel/retry/remove buttons, and overall upload count status.", category: "pickers" },
  { name: "alert", title: "Alert", description: "Notice box with tone bar and status eyebrow.", category: "feedback" },
  { name: "tooltip", title: "Tooltip", description: "Floating helper tooltip on hover and keyboard focus.", category: "feedback" },
  { name: "dialog", title: "Dialog", description: "Accessible modal dialog with focus trap and scale animation.", category: "feedback" },
  { name: "toast", title: "Toast", description: "Transient stacked notices with auto-dismiss.", category: "feedback" },
  { name: "sheet", title: "Sheet", description: "Slide-over drawer panel with focus trap and scroll lock.", category: "feedback" },
  { name: "popover", title: "Popover", description: "Floating content panel anchored to an interactive trigger.", category: "feedback" },
  { name: "empty", title: "Empty", description: "Perforated placeholder box for zero-state views.", category: "data" },
  { name: "spinner", title: "Spinner", description: "Rotary loading indicator with dashed track and stamp accent.", category: "feedback" },
  { name: "skeleton", title: "Skeleton", description: "Dashed placeholder box with gentle pulse animation.", category: "feedback" },
  { name: "cookie-banner", title: "Cookie Banner", description: "Fixed privacy consent banner with accept and decline actions.", category: "feedback" },
  { name: "confetti-burst", title: "Confetti Burst", description: "CSS celebration burst with stamp-colored pieces flying outward.", category: "feedback" },
  { name: "tour", title: "Tour", description: "Interactive step-by-step guided onboarding card with progress indicators.", category: "feedback" },
  { name: "hover-card", title: "Hover Card", description: "Popover preview on hover and focus with configurable delays and alignment.", category: "feedback" },
  { name: "drawer", title: "Drawer", description: "Bottom slide-up drawer with pull handle, backdrop blur, and focus trap.", category: "feedback" },
  { name: "announcement-bar", title: "Announcement Bar", description: "Festival alert and headline announcement ribbon bar with perforated top/bottom tear lines, countdown urgency badge, action CTA button, and dismiss action.", category: "feedback" },
  { name: "status-dot", title: "Status Dot", description: "Live status beacon with radar sweep pulse, glow rings and occupancy levels.", category: "feedback" },
  { name: "donut-chart", title: "Donut Chart", description: "Interactive SVG donut and pie chart with segment hover highlight, tooltips, center total readout, and custom color legend.", category: "charts" },
  { name: "tabs", title: "Tabs", description: "Segmented panel switch with roving keyboard focus.", category: "navigation" },
  { name: "accordion", title: "Accordion", description: "Collapsible disclosure items with smooth height transitions.", category: "data" },
  { name: "pagination", title: "Pagination", description: "Numbered buttons with ellipsis and page stepping.", category: "navigation" },
  { name: "breadcrumb", title: "Breadcrumb", description: "Hierarchical trail with slash separators.", category: "navigation" },
  { name: "steps", title: "Steps", description: "Data-driven wizard progression with numbered stamps.", category: "navigation" },
  { name: "toggle-group", title: "Toggle Group", description: "Single-choice segmented control with roving tabindex.", category: "form" },
  { name: "dropdown-menu", title: "Dropdown Menu", description: "Popup actions menu with keyboard shortcuts and items.", category: "pickers" },
  { name: "countdown", title: "Countdown", description: "Live ticking event timer with segmented cards.", category: "media" },
  { name: "command-palette", title: "Command Palette", description: "Modal search command palette with keyboard shortcuts, categorization, and filter.", category: "navigation" },
  { name: "context-menu", title: "Context Menu", description: "Right-click menu with smooth reveal, shortcuts, and dashed divider.", category: "navigation" },
  { name: "scroll-top", title: "Scroll Top", description: "Floating elevator button that scrolls smoothly to page top.", category: "navigation" },
  { name: "menubar", title: "Menubar", description: "Theater box office menu bar with dropdown menus, shortcuts, and dashed frames.", category: "navigation" },
  { name: "navbar", title: "Navbar", description: "Navigation bar with brand monogram and active links.", category: "navigation" },
  { name: "tree-nav", title: "Tree Nav", description: "Hierarchical explorer with collapsible nodes and icons.", category: "navigation" },
  { name: "sidebar", title: "Sidebar", description: "Collapsible navigation sidebar drawer with notch cutouts.", category: "navigation" },
  { name: "breadcrumb-dropdown", title: "Breadcrumb Dropdown", description: "Hierarchical route breadcrumb with popover dropdown for intermediate tiers.", category: "navigation" },
  { name: "dock", title: "Dock", description: "Floating application dock bar with hover magnification and active indicators.", category: "navigation" },
  { name: "skeleton-v2", title: "Skeleton V2", description: "Shimmer sweep skeleton with text-line and card composition presets.", category: "feedback" },
  { name: "alert-dialog", title: "Alert Dialog", description: "Confirm/cancel modal with destructive variant for irreversible actions, Escape/backdrop close, and animated content.", category: "feedback" },
  { name: "carousel", title: "Carousel", description: "Sliding track carousel with prev/next arrows, dot indicators, keyboard arrows, and optional autoplay.", category: "media" },
  { name: "label", title: "Label", description: "Form label with mono uppercase styling and an animated stamp-red asterisk when required.", category: "form" },
  { name: "form-field", title: "Form Field", description: "Field wrapper with label, control, description, and error message with a shake-in animation on error.", category: "form" },
  { name: "field", title: "Field", description: "Composable field primitives: Field, FieldLabel, FieldControl, FieldDescription, FieldError, FieldGroup, FieldSet.", category: "form" },
  { name: "toggle", title: "Toggle", description: "Two-state button with aria-pressed, springy press animation, and default/outline/accent variants.", category: "form" },
  { name: "navigation-menu", title: "Navigation Menu", description: "Horizontal nav bar whose items reveal an animated panel below with height/fade reveal and sliding indicator.", category: "navigation" },
  { name: "multi-select", title: "Multi Select", description: "Trigger + popover picker with search input, checkbox options, and animated removable selection chips.", category: "pickers" },
  { name: "avatar-group", title: "Avatar Group", description: "Overlapping avatar stack with +N overflow chip that fans out on hover.", category: "data" },
  { name: "divider-with-text", title: "Divider With Text", description: "Centered label over dashed separator lines with a line-grow scaleX animation on mount.", category: "navigation" },
  { name: "input-group", title: "Input Group", description: "Input with prefix icon slot, suffix slot, and inner action button; dashed focus ring and animated underline sweep.", category: "form" },
  { name: "button-group", title: "Button Group", description: "Joins buttons with rounded outer corners, internal separators, and sliding hover highlight.", category: "form" },
  { name: "item", title: "Item", description: "Generic row surface with leading media, title, description, and trailing actions; hover lift with accent bar slide-in.", category: "data" },
  { name: "loading-button", title: "Loading Button", description: "Button with loading spinner swap, width locking to avoid jumps, and a brief success check-mark stamp.", category: "form" },
  { name: "checkbox-group", title: "Checkbox Group", description: "Checkbox options with a select-all row (indeterminate state), animated check fills, and staggered entrance.", category: "form" },
  { name: "listbox", title: "Listbox", description: "Single/multi selectable list with keyboard navigation, ARIA roles, and check marks that slide in.", category: "data" },
  { name: "dropdown-menu-v2", title: "Dropdown Menu V2", description: "V2 dropdown menu: nested submenus, checkbox items, radio groups, separators, danger items, and shortcut kbd hints.", category: "pickers" },
  { name: "heading", title: "Heading", description: "Semantic heading with level-based scale, optional mono eyebrow and per-level entrance animation.", category: "navigation" },
  { name: "text", title: "Text", description: "Typographic paragraph primitive with default, muted, small, lead and mono variants.", category: "navigation" },
  { name: "list", title: "List", description: "List with dashed, numbered and icon variants plus staggered item entrances and List/ListItem composition.", category: "data" },
  { name: "quote", title: "Quote", description: "Blockquote with dashed left frame, stamp entrance and mono uppercase cite line.", category: "data" },
  { name: "figure", title: "Figure", description: "Framed media figure with double-frame surface and delayed figcaption fade-in.", category: "media" },
  { name: "description-list", title: "DescriptionList", description: "Term/description pairs with mono uppercase terms, muted descriptions and staggered row entrances.", category: "data" },
  { name: "page-header", title: "PageHeader", description: "Page title with stamp entrance, fading description, actions slot and optional mono eyebrow.", category: "navigation" },
  { name: "hero", title: "Hero", description: "Landing hero with accent highlight word, primary/secondary actions and bottom marquee strip.", category: "navigation" },
  { name: "footer", title: "Footer", description: "Site footer with brand monogram, staggered link columns and dashed-top bottom bar.", category: "navigation" },
  { name: "media-object", title: "MediaObject", description: "Horizontal media plus content row with title, description, meta chips and hover lift.", category: "media" },
  { name: "link-card", title: "LinkCard", description: "Whole-card link with sliding arrow, darkening border on hover and fade-up entrance.", category: "data" },
  { name: "logo-cloud", title: "LogoCloud", description: "Grid or marquee row of monogram logo tiles in dashed frames with hover reveal.", category: "data" },
  { name: "faq", title: "Faq", description: "Self-contained accordion Q&A with one-open behavior, grid-rows height reveal and rotating plus icon.", category: "data" },
  { name: "testimonial", title: "Testimonial", description: "Quote card with initials avatar, name, role and staggered star rating pop-in.", category: "data" },
  { name: "team-grid", title: "TeamGrid", description: "Grid of member cards with initials avatars, roles, optional links and staggered hover-lift entrances.", category: "data" },
  { name: "feature-grid", title: "FeatureGrid", description: "Feature tiles with icon slot, stamp-on-hover icons, darkening borders and staggered entrance.", category: "data" },
  { name: "cta-section", title: "CtaSection", description: "Double-frame call-to-action band with stamp-seal corner badge and stamping action button.", category: "navigation" },
  { name: "line-chart", title: "Line Chart", description: "Multi-series line chart with stroke-dasharray animation and hover tooltips", category: "charts" },
  { name: "area-chart", title: "Area Chart", description: "Filled area chart with gradient fills and hover highlights", category: "charts" },
  { name: "stacked-bar", title: "Stacked Bar Chart", description: "Horizontal stacked bars with segmented rows and legend chips", category: "charts" },
  { name: "gauge", title: "Gauge", description: "Half-donut SVG gauge with needle animation and value readout", category: "charts" },
  { name: "progress-circle", title: "Progress Circle", description: "Circular progress ring with stroke-dashoffset animation and center percentage", category: "feedback" },
  { name: "radar-chart", title: "Radar Chart", description: "Spider web chart with polygon axes and data polygon animation", category: "charts" },
  { name: "heatmap", title: "Heatmap", description: "Grid of colored cells showing value intensities with diagonal stagger", category: "charts" },
  { name: "calendar-heatmap", title: "Calendar Heatmap", description: "GitHub-style Git calendar heatmap grid", category: "charts" },
  { name: "funnel-chart", title: "Funnel Chart", description: "Horizontal funnel stages showing conversion percentages between steps", category: "charts" },
  { name: "scatter-plot", title: "Scatter Plot", description: "SVG scatter plot with dashed axes and hover enlargements", category: "charts" },
  { name: "waterfall-chart", title: "Waterfall Chart", description: "Floating bars showing incremental changes with connecting guides", category: "charts" },
  { name: "candlestick-chart", title: "Candlestick Chart", description: "OHLC candlestick chart for financial data visualization", category: "charts" },
  { name: "leaderboard", title: "Leaderboard", description: "Ranked leaderboard with medal tiles for top 3 and count-up scores", category: "data" },
  { name: "scoreboard", title: "Scoreboard", description: "Two-team score card with rolling digit animation", category: "ticket-stub" },
  { name: "json-viewer", title: "JSON Viewer", description: "Collapsible JSON tree with mono keys and color-typed values", category: "editors" },
  { name: "diff-viewer", title: "Diff Viewer", description: "Unified diff viewer showing added/removed/context lines", category: "editors" },
  { name: "terminal", title: "Terminal", description: "Fake terminal card with sequential line reveal and blinking cursor", category: "editors" },
  { name: "log-viewer", title: "Log Viewer", description: "Scrolling log stream with level badges and filter chips", category: "editors" },
  { name: "treemap-chart", title: "Treemap Chart", description: "Squarified treemap with recursive rectangles and staggered labels", category: "charts" },
  { name: "confirm-dialog", title: "ConfirmDialog", description: "Self-contained confirm dialog with focus trap and stamp entrance for confirm button in destructive mode.", category: "feedback" },
  { name: "result", title: "Result", description: "Full-panel status screen with icon circle, title, description, and actions slot; confetti-ish subtle burst on success.", category: "feedback" },
  { name: "loading-dots", title: "LoadingDots", description: "Three dots bounce in sequence with keyframe animation; sizes sm/md/lg and tone prop.", category: "feedback" },
  { name: "loading-overlay", title: "LoadingOverlay", description: "Absolute/fixed veil with backdrop blur and spinner; fade in/out with opacity transition.", category: "feedback" },
  { name: "fab", title: "Fab", description: "Floating action button fixed in corner with hover growth, ripple press, and tooltip label on hover.", category: "form" },
  { name: "speed-dial", title: "SpeedDial", description: "FAB that fans out mini action buttons in an arc with staggered scale-in when open; Escape closes.", category: "navigation" },
  { name: "notification-center", title: "NotificationCenter", description: "Bell button with unread badge + dropdown panel with notification rows, mark-all-read, empty state.", category: "feedback" },
  { name: "spotlight", title: "Spotlight", description: "Full-viewport dim overlay with cutout hole positioned via target ref/bounding box; pulse ring around target; caption card.", category: "data" },
  { name: "coach-mark", title: "CoachMark", description: "Single floating tip bubble anchored to trigger children with arrow, title, body, dismiss; pop-in with springy scale.", category: "feedback" },
  { name: "image-compare", title: "ImageCompare", description: "Before/after slider with clip-path inset controlled by draggable divider; BEFORE/AFTER labels.", category: "media" },
  { name: "zoom-image", title: "ZoomImage", description: "Image with hover magnifier lens tracking cursor; framed double border.", category: "media" },
  { name: "infinite-scroll", title: "InfiniteScroll", description: "IntersectionObserver sentinel: when visible calls onLoadMore, shows animated loader row; wraps children.", category: "navigation" },
  { name: "load-more", title: "LoadMore", description: "Button row \"LOAD MORE\" with progress mono counter; on click reveals hidden children with stagger.", category: "navigation" },
  { name: "virtual-list", title: "VirtualList", description: "Windowed list for fixed-height rows: scrollTop math, visible slice renders, spacer divs; smooth scroll.", category: "data" },
  { name: "scroll-shadow", title: "ScrollShadow", description: "Wrapper with top/bottom shadow indicators that fade in only when scrollable in that direction; dashed scrollbar styling.", category: "navigation" },
  { name: "reveal", title: "Reveal", description: "IntersectionObserver: children animate in when entering viewport with fade-up/scale variants, delay prop, once re-trigger option.", category: "media" },
  { name: "product-card", title: "Product Card", description: "Product card with image slot, price, discount badge and wishlist heart.", category: "data" },
  { name: "user-card", title: "User Card", description: "Profile card with avatar, role, meta chips and action slot.", category: "data" },
  { name: "article-card", title: "Article Card", description: "Blog article card with category badge, excerpt and author meta.", category: "data" },
  { name: "event-card", title: "Event Card", description: "Event card with perforated date block, venue and time chips.", category: "data" },
  { name: "invoice", title: "Invoice", description: "Invoice layout with line items, tax breakdown and stamped total.", category: "data" },
  { name: "receipt", title: "Receipt", description: "Thermal receipt with zigzag tear edge, mono lines and barcode footer.", category: "data" },
  { name: "checkout-summary", title: "Checkout Summary", description: "Cart summary with quantity steppers, tax row and checkout CTA.", category: "data" },
  { name: "cart-drawer", title: "Cart Drawer", description: "Slide-over cart drawer with quantity controls and animated removal.", category: "feedback" },
  { name: "size-picker", title: "Size Picker", description: "Size chip picker with out-of-stock strikes and stock dots.", category: "pickers" },
  { name: "variant-picker", title: "Variant Picker", description: "Color swatch and size variant picker with animated selection.", category: "pickers" },
  { name: "wishlist-button", title: "Wishlist Button", description: "Heart wishlist button with pop fill and floating burst.", category: "form" },
  { name: "add-to-cart-button", title: "Add To Cart Button", description: "Add-to-cart button with flying dot arc and check stamp.", category: "form" },
  { name: "order-card", title: "Order Card", description: "Order status card with step dots and item summary.", category: "data" },
  { name: "stamp-card", title: "Stamp Card", description: "Loyalty punch card with stamped circles and reward row.", category: "ticket-stub" },
  { name: "gift-card", title: "Gift Card", description: "Gift card with ribbon stripe, amount and balance bar.", category: "media" },
  { name: "id-card", title: "Id Card", description: "Employee ID card with hologram shine sweep and barcode.", category: "ticket-stub" },
  { name: "rsvp-card", title: "Rsvp Card", description: "Invitation RSVP card with attending toggle and wax stamp.", category: "media" },
  { name: "chat-window", title: "ChatWindow", description: "Full chat panel with message list, input bar, and typing indicator slot.", category: "media" },
  { name: "chat-bubble", title: "ChatBubble", description: "Single message bubble with tail, status ticks, and hover press feedback.", category: "media" },
  { name: "typing-indicator", title: "TypingIndicator", description: "Three bouncing dots with user name label indicating who is typing.", category: "media" },
  { name: "comment-thread", title: "CommentThread", description: "Nested comments with avatars, collapse/reply actions, and dashed indent guides.", category: "media" },
  { name: "reaction-bar", title: "ReactionBar", description: "Emoji buttons with counts, active reaction pops, and hover tooltips.", category: "media" },
  { name: "like-button", title: "LikeButton", description: "Heart/thumb button that fills on click with burst particle animation and count increment.", category: "form" },
  { name: "share-menu", title: "ShareMenu", description: "Platform icon row (X, Facebook, LinkedIn, Link) with copy link feedback and stamp stamp.", category: "media" },
  { name: "story-viewer", title: "StoryViewer", description: "Circular story ring with progress animation, avatar names, and tap zones for prev/next.", category: "media" },
  { name: "post-card", title: "PostCard", description: "Social post with header, body, gradient media placeholder, and action row with like/comment/share counts.", category: "data" },
  { name: "follower-list", title: "FollowerList", description: "Rows with avatars, names, handles, and Follow buttons that morph between states.", category: "data" },
  { name: "voice-message", title: "VoiceMessage", description: "Chat audio bubble with play/pause button and animated waveform bars showing audio duration.", category: "media" },
  { name: "emoji-picker", title: "EmojiPicker", description: "Panel with category tabs (Smileys, Gestures, Hearts, Objects), search filter, and emoji grid with selection callback.", category: "pickers" },
  { name: "audio-player", title: "AudioPlayer", description: "Full deck audio player with play/pause morph button, seek bar, time readout, volume slider, and track info", category: "media" },
  { name: "video-player", title: "VideoPlayer", description: "Video frame with sprocket styling, hover fade-in controls, progress bar with scrub preview", category: "media" },
  { name: "playlist", title: "Playlist", description: "Track rows with equalizer bars for active track, title/artist, duration, and slide-in marker", category: "media" },
  { name: "volume-slider", title: "VolumeSlider", description: "Vertical or horizontal slider with fill animation, mute toggle, and ARIA roles", category: "media" },
  { name: "podcast-player", title: "PodcastPlayer", description: "Episode card with art slot, play button, speed selector chips, skip buttons, and chapter ticks", category: "media" },
  { name: "video-thumbnail", title: "VideoThumbnail", description: "Poster frame with duration badge, play overlay circle that scales on hover with ripple ring, and title strip", category: "media" },
  { name: "media-controls", title: "MediaControls", description: "Compact transport bar with prev/play/next/stop buttons, progress micro-bar, and time display", category: "media" },
  { name: "live-badge", title: "LiveBadge", description: "LIVE indicator with blinking dot, mono uppercase label, and optional viewer count that ticks", category: "feedback" },
  { name: "time-ago", title: "TimeAgo", description: "Relative time display showing '5 MIN AGO' with live re-render tick every 30s", category: "media" },
  { name: "live-clock", title: "LiveClock", description: "Digital clock showing HH:MM:SS with optional timezone and variant support", category: "media" },
  { name: "typewriter", title: "Typewriter", description: "Types text char-by-char with blinking block cursor, loops through phrases", category: "media" },
  { name: "highlight-text", title: "HighlightText", description: "Highlights query matches inside text with accent background and animated reveal", category: "media" },
  { name: "truncate", title: "Truncate", description: "Single/multi-line clamp with optional expand toggle (MORE/LESS)", category: "media" },
  { name: "text-diff", title: "TextDiff", description: "Word-level diff showing added/removed words with animation", category: "editors" },
  { name: "currency-display", title: "CurrencyDisplay", description: "Formatted money with symbol, mono integer part, smaller muted decimals, optional count-up animation", category: "data" },
  { name: "copy-chip", title: "CopyChip", description: "Small mono chip that copies to clipboard with check morph and 'COPIED' feedback", category: "form" },
  { name: "receipt-printer", title: "ReceiptPrinter", description: "Thermal printer that feeds mono receipt lines out of a printer slot with a stepped paper animation.", category: "data" },
  { name: "queue-ticket", title: "QueueTicket", description: "Take-a-number queue ticket with a big tear-off number tab, NOW SERVING ring and queue stats.", category: "ticket-stub" },
  { name: "now-serving", title: "NowServing", description: "Split-flap style NOW SERVING board whose digits flip on value change with a blinking chime dot.", category: "data" },
  { name: "passport", title: "Passport", description: "Double-frame passport cover with monogram, holder fields and staggered visa stamp marks.", category: "ticket-stub" },
  { name: "wax-seal", title: "WaxSeal", description: "Circular wax blob with a pressed-in monogram entrance and an optional cracked break state.", category: "ticket-stub" },
  { name: "envelope", title: "Envelope", description: "Envelope whose flap opens with a 3D rotateX and the letter inside rises, on hover or via an open prop.", category: "ticket-stub" },
  { name: "airmail-letter", title: "AirmailLetter", description: "Airmail bordered letter with red/blue diagonal stripes, mono lines, a postmark corner and an unfold entrance.", category: "ticket-stub" },
  { name: "postmark", title: "Postmark", description: "Circular postal cancellation stamp with wavy lines, city and date arcs that stamps in on mount.", category: "ticket-stub" },
  { name: "cassette-tape", title: "CassetteTape", description: "Cassette with two spinning reels, shifting tape amounts and a handwritten-style label with play toggle.", category: "ticket-stub" },
  { name: "vinyl-record", title: "VinylRecord", description: "Spinning vinyl with radial grooves, center label, a tonearm that slides in and a wobble on drop.", category: "ticket-stub" },
  { name: "flip-clock", title: "FlipClock", description: "Mechanical split-flap HH:MM clock whose digit cards flip on change with a blinking colon.", category: "ticket-stub" },
  { name: "neon-sign", title: "NeonSign", description: "Neon sign with layered glow text-shadow, flicker-in entrance and a subtle per-letter buzz.", category: "ticket-stub" },
  { name: "marquee-bulbs", title: "MarqueeBulbs", description: "Marquee board framed by chase-blinking bulbs with scrolling center text.", category: "ticket-stub" },
  { name: "backstage-pass", title: "BackstagePass", description: "Laminated ALL ACCESS pass with lanyard hole, rotated stripe strip, shine sweep on hover and fake barcode.", category: "ticket-stub" },
  { name: "wristband", title: "Wristband", description: "Festival wristband with patterned repeating stripes, snap closure, serial and a subtle breathing animation.", category: "ticket-stub" },
  { name: "lanyard", title: "Lanyard", description: "Strap with clip that sways gently from the top and holds an attached card slot for children.", category: "ticket-stub" },
  { name: "drink-ticket", title: "DrinkTicket", description: "Perforated drink coupon with glyph, GOOD FOR ONE copy and a tear-off stub that rotates on hover.", category: "ticket-stub" },
  { name: "raffle-ticket", title: "RaffleTicket", description: "Raffle ticket with a big number, matching stub number and a winning highlight that pulses and stamps.", category: "ticket-stub" },
  { name: "slot-machine", title: "SlotMachine", description: "Three-reel slot machine with staggered spinning reels, a pulling lever and payline highlight on stop.", category: "ticket-stub" },
  { name: "prize-wheel", title: "PrizeWheel", description: "SVG prize wheel of tinted segments that spins with eased deceleration and a flicking pointer flapper.", category: "ticket-stub" },
  { name: "dice", title: "Dice", description: "Pair of 3D dice that tumble with rapid face swaps and settle with a bounce on roll.", category: "ticket-stub" },
  { name: "coin-flip", title: "CoinFlip", description: "Coin that rotates on Y through multiple turns, decelerating to a heads or tails face with a stamped result badge.", category: "ticket-stub" },
  { name: "playing-card", title: "PlayingCard", description: "Playing card with corner rank and suit, big center suit, diamond-pattern back and a 3D flip on click.", category: "ticket-stub" },
  { name: "bingo-card", title: "BingoCard", description: "5x5 B-I-N-G-O card whose cells stamp in on toggle with a free center and line-complete sweep highlights.", category: "ticket-stub" },
  { name: "jumbotron", title: "Jumbotron", description: "Oversized scoreboard with pixel-style mono type, scanline sweep and scoreboard slots for home and away.", category: "navigation" },
  { name: "fireworks", title: "Fireworks", description: "Rockets that rise and burst into radial particle rings, looping while active.", category: "feedback" },
  { name: "disco-ball", title: "DiscoBall", description: "Tiled mirror sphere that slowly rotates and projects dancing light dots around the room.", category: "ticket-stub" },
  { name: "stage-lights", title: "StageLights", description: "Two to four gradient light cones that sweep alternately over a glowing stage floor ellipse.", category: "ticket-stub" },
  { name: "ticket-booth", title: "TicketBooth", description: "Booth window with TICKETS marquee header, counter ledge, speaker grille dots and a CLOSED flip sign.", category: "ticket-stub" },
  { name: "drive-in-screen", title: "DriveInScreen", description: "Outdoor cinema screen with projection flicker, a car silhouette row and an intermission countdown slot.", category: "ticket-stub" },
  { name: "ticket-stub-v2", title: "TicketStubV2", description: "Rip-off event stub whose tear line detaches the stub with rotate-and-fall on tear, plus serial and barcode.", category: "ticket-stub" },
  { name: "tabbar", title: "TabBar", description: "Fixed bottom navigation bar with sliding active indicator pill and badge support", category: "navigation" },
  { name: "pager-dots", title: "PagerDots", description: "Navigation page indicators with active dot that stretches and variant styles", category: "navigation" },
  { name: "toc", title: "Toc", description: "Table of contents with IntersectionObserver scroll-spy and dashed active underline", category: "navigation" },
  { name: "app-shell", title: "AppShell", description: "Page skeleton with top bar, collapsible sidebar, and main content area with built-in skip-link", category: "navigation" },
  { name: "skip-link", title: "SkipLink", description: "Accessibility skip-link that becomes visible on keyboard focus with translate animation", category: "navigation" },
  { name: "back-link", title: "BackLink", description: "Chevron button with label that slides on hover, with focus ring", category: "navigation" },
  { name: "flyout-menu", title: "FlyoutMenu", description: "Hover dropdown menu with scale-in origin-top panel and keyboard navigation", category: "navigation" },
  { name: "scroll-spy-nav", title: "ScrollSpyNav", description: "Horizontal sticky navigation with active pill that slides under the active section, smooth scroll with reduced-motion fallback", category: "navigation" },
  { name: "phone-input", title: "PhoneInput", description: "Phone number input with country code selector and formatted display", category: "pickers" },
  { name: "email-input", title: "EmailInput", description: "Email input with live validation and typo domain suggestions", category: "form" },
  { name: "date-range-picker", title: "DateRangePicker", description: "Two-month mini calendar grid for selecting start and end dates with nights count", category: "pickers" },
  { name: "month-picker", title: "MonthPicker", description: "12-month grid for selecting a month with year navigation", category: "pickers" },
  { name: "year-picker", title: "YearPicker", description: "Year grid with page navigation for selecting a year", category: "pickers" },
  { name: "time-range-picker", title: "TimeRangePicker", description: "Two time inputs with duration readout that animates on change", category: "pickers" },
  { name: "clock-picker", title: "ClockPicker", description: "Analog clock with draggable hands for time selection", category: "pickers" },
  { name: "hotkey-recorder", title: "HotkeyRecorder", description: "Record keyboard hotkey combinations with visual chip display", category: "pickers" },
  { name: "file-input", title: "FileInput", description: "Styled file input with drop chips and selection count animation", category: "pickers" },
  { name: "slider-ticks", title: "SliderTicks", description: "Slider with tick marks, labels, and snap-to-ticks functionality", category: "form" },
  { name: "qr-code", title: "QR Code", description: "Generates QR codes with Reed-Solomon error correction, mask evaluation, and finder patterns. Includes encodeQrMatrix helper.", category: "ticket-stub" },
  { name: "rich-text-editor", title: "Rich Text Editor", description: "Minimal contentEditable editor with toolbar (bold, italic, underline, lists, links, quote, code) and word/char counter.", category: "editors" },
  { name: "image-crop", title: "Image Crop", description: "Canvas-based image cropping with draggable crop rect, rule-of-thirds grid, resize handles, and dataURL output.", category: "pickers" },
  { name: "sankey-chart", title: "Sankey Chart", description: "Two-level flow diagram with bezier ribbons, value-based width, hover tooltips, and entrance animations.", category: "charts" },
  { name: "org-chart", title: "Org Chart", description: "Hierarchical tree of boxes with connector lines, expand/collapse nodes, avatar initials, and entrance animations.", category: "charts" },
  { name: "hooks", title: "Hooks", description: "SSR-safe React hooks: media query, localStorage, intersection, click-outside, copy, hotkey, and debounce.", category: "form" },
  { name: "focus-trap", title: "Focus Trap", description: "Pure TypeScript focus trapping helpers for accessible overlays: getFocusable and trapFocus.", category: "form" },
  { name: "tilt-card", title: "Tilt Card", description: "3D cursor-tracking tilt card with springy reset and glare highlight.", category: "data", isNew: true },
  { name: "flip-card", title: "Flip Card", description: "Two-face card with rotateY flip animation, hover or click trigger.", category: "data", isNew: true },
  { name: "spotlight-card", title: "Spotlight Card", description: "Card with cursor-following radial spotlight glow.", category: "data", isNew: true },
  { name: "drag-sort", title: "Drag Sort", description: "HTML5 drag-and-drop reorderable list with grab handles and drop indicators.", category: "data", isNew: true },
  { name: "login-form", title: "Login Form", description: "Login form with live validation, show/hide password, remember me and social buttons.", category: "form", isNew: true },
  { name: "register-form", title: "Register Form", description: "Registration form with name, email, animated password strength and terms consent.", category: "form", isNew: true },
  { name: "forgot-password", title: "Forgot Password", description: "Password reset flow: email input transitions to animated sent confirmation.", category: "form", isNew: true },
  { name: "otp-verify", title: "Otp Verify", description: "6-digit OTP verification with auto-advance, paste support and resend countdown.", category: "pickers", isNew: true },
  { name: "two-factor", title: "Two Factor", description: "2FA setup panel with animated QR scan line, recovery codes and copy action.", category: "pickers", isNew: true },
  { name: "session-list", title: "Session List", description: "Active session manager: device icons, location, revoke buttons.", category: "data", isNew: true },
  { name: "api-key-card", title: "Api Key Card", description: "API key card with masked value, reveal toggle, copy and regenerate actions.", category: "editors", isNew: true },
  { name: "permissions-matrix", title: "Permissions Matrix", description: "Role � permission checkbox matrix with animated check pops.", category: "editors", isNew: true },
  { name: "audit-log", title: "Audit Log", description: "Audit trail with actor avatars, color-coded action badges and timestamps.", category: "editors", isNew: true },
  { name: "security-score", title: "Security Score", description: "Security score with animated arc gauge and per-check pass/fail list.", category: "feedback", isNew: true },
  { name: "admin-shell", title: "Admin Shell", description: "Admin panel skeleton: collapsible sidebar nav, top bar, content area.", category: "navigation", isNew: true },
  { name: "stats-overview", title: "Stats Overview", description: "Overview layout: KPI tile row, mini bar chart panel and recent records table.", category: "data", isNew: true },
  { name: "user-table", title: "User Table", description: "User management table with role badges, status dots and remove action.", category: "data", isNew: true },
  { name: "role-badge", title: "Role Badge", description: "Role badge set: admin, editor, member, viewer with distinct tones.", category: "feedback", isNew: true },
  { name: "settings-section", title: "Settings Section", description: "Settings section: title, description rows and save confirmation stamp.", category: "data", isNew: true },
  { name: "profile-settings", title: "Profile Settings", description: "Profile settings with avatar slot, fields and animated danger zone.", category: "data", isNew: true },
  { name: "danger-zone", title: "Danger Zone", description: "Red-framed destructive actions area with two-step confirm.", category: "feedback", isNew: true },
  { name: "billing-panel", title: "Billing Panel", description: "Billing panel: plan card, usage meters and invoice list.", category: "data", isNew: true },
  { name: "usage-meter", title: "Usage Meter", description: "Quota meter with color-coded fill bar and over-limit pulse warning.", category: "data", isNew: true },
  { name: "team-members", title: "Team Members", description: "Team member management: invite input, role chips, remove action.", category: "data", isNew: true },
  { name: "invite-modal", title: "Invite Modal", description: "Invite modal with email, role radio group and sent confirmation.", category: "feedback", isNew: true },
  { name: "webhook-list", title: "Webhook List", description: "Webhook list with URL, event chips, test button and remove.", category: "editors", isNew: true },
  { name: "upgrade-prompt", title: "Upgrade Prompt", description: "Upgrade call-to-action card with shine sweep, feature list and dismiss.", category: "feedback", isNew: true },
  { name: "maintenance-banner", title: "Maintenance Banner", description: "Maintenance notification bar with countdown chip and dismiss.", category: "feedback", isNew: true },
  { name: "offline-banner", title: "Offline Banner", description: "Offline banner listening to navigator.onLine with reconnecting state.", category: "feedback", isNew: true },
  { name: "error-page", title: "Error Page", description: "404/500/403 full-page layout with stamped code and return action.", category: "feedback", isNew: true },
  { name: "permission-denied", title: "Permission Denied", description: "Access denied panel with lock icon and request-access flow.", category: "feedback", isNew: true },
  { name: "form-progress", title: "Form Progress", description: "Form completion progress with segmented dashed bars.", category: "form", isNew: true },
  { name: "save-indicator", title: "Save Indicator", description: "Auto-save status chip: idle, saving, saved, error states.", category: "feedback", isNew: true },
  { name: "connection-status", title: "Connection Status", description: "Connection badge with pinging dot and optional latency readout.", category: "feedback", isNew: true },
  { name: "version-badge", title: "Version Badge", description: "Version badge set: new, beta, stable, deprecated tones.", category: "feedback", isNew: true },
  { name: "feature-flag-panel", title: "Feature Flag Panel", description: "Feature flag panel with toggle switches and rollout percentages.", category: "editors", isNew: true },
  { name: "sync-status", title: "Sync Status", description: "Sync status chip with spinning icon and last-sync timestamp.", category: "feedback", isNew: true },
  { name: "queued-jobs", title: "Queued Jobs", description: "Job queue panel with status, progress bars and cancel action.", category: "editors", isNew: true },
  { name: "upload-progress", title: "Upload Progress", description: "Single file upload with circular progress ring and cancel.", category: "feedback", isNew: true },
  { name: "migration-banner", title: "Migration Banner", description: "Data migration banner with progress bar and expandable detail.", category: "feedback", isNew: true },
  { name: "rate-limit-note", title: "Rate Limit Note", description: "Rate limit notice with countdown timer.", category: "feedback", isNew: true },
  { name: "bento-grid", title: "Bento Grid", description: "Bento grid: variable-sized cells with hover lift and staggered entrance.", category: "data", isNew: true },
  { name: "split-screen", title: "Split Screen", description: "Split layout: left content and right emphasis panel with ratio control.", category: "data", isNew: true },
  { name: "sticky-footer", title: "Sticky Footer", description: "Sticky bottom bar that stays visible during scroll.", category: "navigation", isNew: true },
  { name: "centered-card", title: "Centered Card", description: "Centered single card layout for login/register pages.", category: "data", isNew: true },
  { name: "two-column-list", title: "Two Column List", description: "Two-column notebook-style list with dashed separators.", category: "data", isNew: true },
  { name: "masonry-columns", title: "Masonry Columns", description: "CSS columns masonry: cards flow by height with break-inside protection.", category: "data", isNew: true },
  { name: "hero-split", title: "Hero Split", description: "Split hero: left text block and right framed visual slot.", category: "navigation", isNew: true },
  { name: "footer-minimal", title: "Footer Minimal", description: "Single-row minimal footer: brand, links, copyright.", category: "navigation", isNew: true },
  { name: "responsive-nav", title: "Responsive Nav", description: "Auto-switching nav: desktop horizontal links, mobile hamburger panel.", category: "navigation", isNew: true },
  { name: "keyboard-nav-helper", title: "Keyboard Nav Helper", description: "Keyboard shortcut overlay opened with the ? key.", category: "navigation", isNew: true },
  { name: "data-grid", title: "Data Grid", description: "Heavy data grid: sortable columns, pagination, sticky header.", category: "data", isNew: true },
  { name: "tree-table", title: "Tree Table", description: "Hierarchical table rows with expand/collapse chevrons.", category: "data", isNew: true },
  { name: "kanban-v2", title: "Kanban V2", description: "Drag-and-drop kanban board v2 with animated column transfers.", category: "data", isNew: true },
  { name: "board-checklist", title: "Board Checklist", description: "Task checklist: checkboxes, assignee, priority badges and progress bar.", category: "data", isNew: true },
  { name: "task-list", title: "Task List", description: "Task rows with assignee chips and priority badges.", category: "data", isNew: true },
  { name: "timeline-vertical-v2", title: "Timeline Vertical V2", description: "Two-sided vertical timeline v2 with alternating cards.", category: "data", isNew: true },
  { name: "feed-masonry", title: "Feed Masonry", description: "Masonry feed of mixed-height content cards.", category: "data", isNew: true },
  { name: "inbox-list", title: "Inbox List", description: "Email inbox list: unread dots, senders, stars, subject previews.", category: "data", isNew: true },
  { name: "notification-feed", title: "Notification Feed", description: "Full-page notification feed with type icons and read states.", category: "feedback", isNew: true },
  { name: "activity-v2", title: "Activity V2", description: "Filterable activity feed v2 with action badges and avatars.", category: "data", isNew: true },
  { name: "rank-list", title: "Rank List", description: "Ranked list with drag-to-reorder and score readouts.", category: "data", isNew: true },
  { name: "table-summary", title: "Table Summary", description: "Table footer summary rows with bolded totals in dashed frame.", category: "data", isNew: true },
  { name: "empty-col-span", title: "Empty Col Span", description: "Empty table cell placeholder with floating icon animation.", category: "data", isNew: true },
  { name: "row-expand", title: "Row Expand", description: "Expandable row detail panels with height animation.", category: "data", isNew: true },
  { name: "column-toggle", title: "Column Toggle", description: "Column show/hide dropdown menu for data grids.", category: "data", isNew: true },
  { name: "wizard", title: "Wizard", description: "Multi-step wizard with validation shake, progress markers and summary.", category: "navigation", isNew: true },
  { name: "stepper-v2", title: "Stepper V2", description: "Vertical/horizontal stepper v2 with descriptions and done states.", category: "form", isNew: true },
  { name: "mega-menu", title: "Mega Menu", description: "Full-width mega menu with columns, links and featured box.", category: "navigation", isNew: true },
  { name: "drawer-nav", title: "Drawer Nav", description: "Mobile hamburger drawer sliding from the left with staggered links.", category: "feedback", isNew: true },
  { name: "footer-nav", title: "Footer Nav", description: "Site-map footer with link columns.", category: "navigation", isNew: true },
  { name: "anchor-nav", title: "Anchor Nav", description: "Sticky section anchor nav with IntersectionObserver spy.", category: "navigation", isNew: true },
  { name: "quick-actions", title: "Quick Actions", description: "Quick action toolbar with shortcuts and danger variants.", category: "navigation", isNew: true },
  { name: "history-nav", title: "History Nav", description: "Back/forward history strip with breadcrumb entries.", category: "navigation", isNew: true },
  { name: "page-tabs", title: "Page Tabs", description: "In-page tabs synced to URL query parameter.", category: "navigation", isNew: true },
  { name: "mobile-menu", title: "Mobile Menu", description: "Full-screen mobile menu with staggered link entrance.", category: "navigation", isNew: true },
  { name: "sidebar-v2", title: "Sidebar V2", description: "Two-level collapsible sidebar v2.", category: "navigation", isNew: true },
  { name: "flyout-v2", title: "Flyout V2", description: "Hover flyout menu v2 with keyboard support.", category: "navigation", isNew: true },
  { name: "scroll-spy-v2", title: "Scroll Spy V2", description: "Horizontal scroll-spy nav v2 with sliding active pill.", category: "navigation", isNew: true },
  { name: "pagination-v2", title: "Pagination V2", description: "Hybrid pagination: numbered plus infinite scroll trigger.", category: "navigation", isNew: true },
  { name: "search-filter-bar", title: "Search Filter Bar", description: "Combined search, sort and filter toolbar with animated chips.", category: "form", isNew: true },
  { name: "mention-list", title: "Mention List", description: "@mention suggestion panel with avatars and keyboard highlight.", category: "media", isNew: true },
  { name: "dm-thread", title: "Dm Thread", description: "Direct message thread: header with presence, bubbles, input.", category: "media", isNew: true },
  { name: "poll", title: "Poll", description: "Interactive poll with animated result bars and vote confirmation.", category: "media", isNew: true },
  { name: "quiz-card", title: "Quiz Card", description: "Mini quiz card with options and correct/incorrect feedback.", category: "data", isNew: true },
  { name: "avatar-upload", title: "Avatar Upload", description: "Avatar upload circle with hover camera overlay and preview.", category: "pickers", isNew: true },
  { name: "bio-card", title: "Bio Card", description: "Bio card with social link icons and follow action.", category: "data", isNew: true },
  { name: "mention-highlight", title: "Mention Highlight", description: "Highlight @mentions and #hashtags inside running text.", category: "media", isNew: true },
  { name: "badge-list", title: "Badge List", description: "Achievement badge grid with earned/locked states and shine sweep.", category: "data", isNew: true },
  { name: "gift-message", title: "Gift Message", description: "Gift message card with ribbon wiggle and open animation.", category: "media", isNew: true },
  { name: "voice-note-list", title: "Voice Note List", description: "Voice note list: play buttons, waveforms, durations.", category: "media", isNew: true },
  { name: "price-compare", title: "Price Compare", description: "Price comparison table across sellers with best-offer highlight.", category: "data", isNew: true },
  { name: "stock-status", title: "Stock Status", description: "Stock status badge: in stock, low stock pulse, sold out.", category: "feedback", isNew: true },
  { name: "shipping-options", title: "Shipping Options", description: "Shipping option radio cards with carrier, duration and price.", category: "form", isNew: true },
  { name: "payment-methods", title: "Payment Methods", description: "Payment method selector with card, bank, cash, wallet icons.", category: "form", isNew: true },
  { name: "credit-card-form", title: "Credit Card Form", description: "Credit card form with live number formatting and expiry mask.", category: "form", isNew: true },
  { name: "installment-picker", title: "Installment Picker", description: "Installment plan picker: months, monthly amount, total.", category: "form", isNew: true },
  { name: "coupon-field", title: "Coupon Field", description: "Coupon code field with validation, success check and shake error.", category: "form", isNew: true },
  { name: "cart-badge", title: "Cart Badge", description: "Cart count badge that pulses on item add.", category: "data", isNew: true },
  { name: "order-tracking", title: "Order Tracking", description: "Order tracking strip: status dots with dates and courier.", category: "data", isNew: true },
  { name: "refund-card", title: "Refund Card", description: "Refund status card with amount and reason.", category: "data", isNew: true },
  { name: "wallet-card", title: "Wallet Card", description: "Wallet balance card with top-up and mini transactions.", category: "data", isNew: true },
  { name: "crypto-ticker", title: "Crypto Ticker", description: "Crypto price ticker with animated up/down arrows.", category: "data", isNew: true },
  { name: "exchange-rate", title: "Exchange Rate", description: "Exchange rate converter with two-way live calculation.", category: "data", isNew: true },
  { name: "budget-progress", title: "Budget Progress", description: "Budget spending bar with category breakdown and overrun warning.", category: "data", isNew: true },
  { name: "subscription-card", title: "Subscription Card", description: "Subscription card: plan, renewal date, features, cancel.", category: "data", isNew: true },
  { name: "gallery-grid", title: "Gallery Grid", description: "Image gallery grid with fullscreen lightbox and keyboard paging.", category: "data", isNew: true },
  { name: "image-carousel", title: "Image Carousel", description: "Image carousel with arrows, dots and swipe feel.", category: "media", isNew: true },
  { name: "thumbnail-strip", title: "Thumbnail Strip", description: "Horizontal thumbnail strip with animated selection frame.", category: "media", isNew: true },
  { name: "video-list", title: "Video List", description: "Video results list: thumbnails, duration badges, channel names.", category: "media", isNew: true },
  { name: "audio-recorder", title: "Audio Recorder", description: "Microphone recording simulator with waveform and send action.", category: "media", isNew: true },
  { name: "media-embed", title: "Media Embed", description: "Embedded media frame: 16:9, skeleton shimmer, dashed border.", category: "media", isNew: true },
  { name: "poster-card", title: "Poster Card", description: "Event poster card with gradient overlay and date corner.", category: "data", isNew: true },
  { name: "screenshot-frame", title: "Screenshot Frame", description: "Browser-chrome screenshot frame with URL bar and controls.", category: "media", isNew: true },
  { name: "quote-wall", title: "Quote Wall", description: "Masonry quote wall built on Quote cards.", category: "data", isNew: true },
  { name: "glossary-list", title: "Glossary List", description: "Glossary list with letter index tabs and term definitions.", category: "data", isNew: true },
  { name: "changelog-list", title: "Changelog List", description: "Changelog list: version badges, added/fixed/breaking sections.", category: "data", isNew: true },
  { name: "recipe-card", title: "Recipe Card", description: "Recipe card: ingredients/steps tabs, time and servings.", category: "data", isNew: true },
  { name: "code-editor", title: "Code Editor", description: "Code editor: line-number gutter, Tab insertion, scroll sync.", category: "editors", isNew: true },
  { name: "markdown-editor", title: "Markdown Editor", description: "Markdown write/preview tabs with built-in renderer.", category: "editors", isNew: true },
  { name: "markdown-preview", title: "Markdown Preview", description: "Standalone markdown renderer: headings, lists, code, links, bold.", category: "editors", isNew: true },
  { name: "html-preview", title: "Html Preview", description: "Sandboxed HTML preview frame.", category: "editors", isNew: true },
  { name: "diff-editor", title: "Diff Editor", description: "Editable side-by-side diff view.", category: "editors", isNew: true },
  { name: "json-editor", title: "Json Editor", description: "JSON editor with live validation, error line and format button.", category: "editors", isNew: true },
  { name: "regex-tester", title: "Regex Tester", description: "Regex tester: pattern, test string, highlighted matches and count.", category: "editors", isNew: true },
  { name: "cron-builder", title: "Cron Builder", description: "Cron expression builder: 5 fields, presets, live description.", category: "editors", isNew: true },
  { name: "color-token-table", title: "Color Token Table", description: "Theme token table: swatch, value, copy action.", category: "editors", isNew: true },
  { name: "snippet-card", title: "Snippet Card", description: "Code snippet card with language badge and copy button.", category: "editors", isNew: true },
  { name: "console-panel", title: "Console Panel", description: "Console panel: colored output lines, input row, autoscroll.", category: "editors", isNew: true },
  { name: "env-editor", title: "Env Editor", description: "Environment variable editor: secret masking, add/remove rows.", category: "editors", isNew: true },
  { name: "world-map", title: "World Map", description: "Stylized world map grid with region value intensity and hover readout.", category: "charts", isNew: true },
  { name: "bubble-chart", title: "Bubble Chart", description: "Bubble chart with size-coded circles and hover magnify.", category: "charts", isNew: true },
  { name: "word-cloud", title: "Word Cloud", description: "Word cloud with weight-based font sizing and hover accent.", category: "charts", isNew: true },
  { name: "network-graph", title: "Network Graph", description: "Node-edge network graph with bezier links and hover highlight.", category: "charts", isNew: true },
  { name: "sunburst-chart", title: "Sunburst Chart", description: "Two-ring sunburst chart with segment hover dimming.", category: "charts", isNew: true },
  { name: "checkbox-card", title: "Checkbox Card", description: "Card-style checkbox with title, description and check pop.", category: "form", isNew: true },
  { name: "radio-tile", title: "Radio Tile", description: "Radio tile with icon, description and sliding dot.", category: "form", isNew: true },
  { name: "switch-card", title: "Switch Card", description: "Switch card combining title, description and toggle.", category: "form", isNew: true },
  { name: "field-array", title: "Field Array", description: "Dynamic form rows: add, remove, move up/down.", category: "pickers", isNew: true },
  { name: "textarea-autosize", title: "Textarea Autosize", description: "Auto-growing textarea with min/max height bounds.", category: "form", isNew: true },
  { name: "char-counter", title: "Char Counter", description: "Character counter with near-limit and over-limit states.", category: "form", isNew: true },
  { name: "password-input", title: "Password Input", description: "Password input with animated show/hide eye toggle.", category: "form", isNew: true },
  { name: "consent-checkbox", title: "Consent Checkbox", description: "GDPR/KVKK consent checkbox with link and required marker.", category: "form", isNew: true },
  { name: "address-form", title: "Address Form", description: "Address form grid: street, city, district, postal, country.", category: "form", isNew: true },
  { name: "currency-select", title: "Currency Select", description: "Currency select dropdown with symbols and codes.", category: "pickers", isNew: true },
  { name: "country-select", title: "Country Select", description: "Country select with flag emojis and codes.", category: "pickers", isNew: true },
  { name: "duration-input", title: "Duration Input", description: "Duration input: hour/minute/second steppers.", category: "pickers", isNew: true },
  { name: "serial-input", title: "Serial Input", description: "Serial number input: grouped boxes, auto-advance, paste support.", category: "pickers", isNew: true },
  { name: "lottery-machine", title: "Lottery Machine", description: "Lottery machine with shaking ball cage and stamped number results.", category: "ticket-stub", isNew: true },
  { name: "ticket-validator", title: "Ticket Validator", description: "Ticket validator device with blinking green/red result light.", category: "ticket-stub", isNew: true },
  { name: "vending-machine", title: "Vending Machine", description: "Vending machine with product grid, coin slot and drop animation.", category: "ticket-stub", isNew: true },
  { name: "arcade-cabinet", title: "Arcade Cabinet", description: "Retro arcade cabinet with scanline screen, joystick and coin slot.", category: "ticket-stub", isNew: true },
  { name: "betting-slip", title: "Betting Slip", description: "Betting slip: match picks, odds grid, stake and play button.", category: "ticket-stub", isNew: true },
  { name: "punch-clock", title: "Punch Clock", description: "Punch clock with live digital time and in/out stamp feed.", category: "ticket-stub", isNew: true },
  { name: "mailbox", title: "Mailbox", description: "Mailbox with flag raise and letter send animation.", category: "ticket-stub", isNew: true },
  { name: "safe-vault", title: "Safe Vault", description: "Safe vault with dial animation, code entry and open reveal.", category: "ticket-stub", isNew: true },
  { name: "medal-display", title: "Medal Display", description: "Medal board with gold/silver/bronze tiers and shine sweep.", category: "ticket-stub", isNew: true },
  { name: "trophy-shelf", title: "Trophy Shelf", description: "Trophy shelf with earned/empty slots and drop-in animation.", category: "ticket-stub", isNew: true },
  { name: "megaphone", title: "Megaphone", description: "Announcement megaphone with animated sound waves.", category: "media", isNew: true },
  { name: "score-keeper", title: "Score Keeper", description: "Two-team score keeper with pulse on score change.", category: "data", isNew: true },
  { name: "match-ticker", title: "Match Ticker", description: "Live match ticker with scrolling scores and LIVE badges.", category: "data", isNew: true },
  { name: "pool-table", title: "Pool Table", description: "Pool ball grid organizer with striped/solid ball rendering.", category: "ticket-stub", isNew: true },
  { name: "revolving-door", title: "Revolving Door", description: "Revolving door with rotating panels.", category: "ticket-stub", isNew: true },
  { name: "ferris-wheel", title: "Ferris Wheel", description: "Ferris wheel with rotating cabins.", category: "ticket-stub", isNew: true },
  { name: "carousel-ride", title: "Carousel Ride", description: "Carousel ride with circling horses.", category: "ticket-stub", isNew: true },
  { name: "badge-ribbon", title: "Badge Ribbon", description: "Award rosette badge ribbon with swallow-tail streamers and certified stamp.", category: "ticket-stub", isNew: true },
  { name: "bullet-chart", title: "Bullet Chart", description: "Target versus actual progress meter with qualitative ranges and goal marker.", category: "charts", isNew: true },
  { name: "callout", title: "Callout", description: "Tactile admission callout note with dashed borders, status tones and dismiss action.", category: "feedback", isNew: true },
  { name: "histogram", title: "Histogram", description: "Frequency distribution histogram with hover count readout and grow animation.", category: "charts", isNew: true },
  { name: "meter", title: "Meter", description: "Turnstile capacity meter with notched frame, optimal indicator and tick marks.", category: "feedback", isNew: true },
  { name: "milestone-chart", title: "Milestone Chart", description: "Horizontal milestone timeline progress line with reached checkpoints.", category: "charts", isNew: true },
  { name: "radio-cards", title: "Radio Cards", description: "Rich selectable radio cards with prices, perks and active ticket border.", category: "form", isNew: true },
  { name: "route-loader", title: "Route Loader", description: "Minimal top progress loader bar with smooth transit animation.", category: "navigation", isNew: true },
  { name: "split-button", title: "Split Button", description: "Dual-action button with primary click trigger and dropdown secondary actions.", category: "form", isNew: true },
  { name: "stat-tile", title: "Stat Tile", description: "KPI metric box with big tabular numbers, delta change and sparkline bars.", category: "data", isNew: true },
  { name: "trend-badge", title: "Trend Badge", description: "Dynamic rate and velocity indicator badge with live pulse indicator.", category: "feedback", isNew: true },
];
