export type ComponentCategory = "form" | "display" | "feedback" | "navigation";

export type ComponentMeta = {
  name: string;
  title: string;
  description: string;
  category: ComponentCategory;
};

export const categories: { id: ComponentCategory; name: string; description: string }[] = [
  { id: "form", name: "Form", description: "Inputs, pickers, toggles and tactile controls." },
  { id: "display", name: "Display", description: "Surfaces, badges and data frames." },
  { id: "feedback", name: "Feedback", description: "Overlays, notices, sheets and loading states." },
  { id: "navigation", name: "Navigation", description: "Tabs, steps, breadcrumbs, menus and timers." },
];

export const components: ComponentMeta[] = [
  // Form (14)
  { name: "button", title: "Button", description: "Animated button with hover feedback and crisp focus.", category: "form" },
  { name: "input", title: "Input", description: "Text input with dashed focus border and design tokens.", category: "form" },
  { name: "textarea", title: "Textarea", description: "Multi-line text area matching Input styling.", category: "form" },
  { name: "checkbox", title: "Checkbox", description: "Crisp checkbox with bold checked states.", category: "form" },
  { name: "switch", title: "Switch", description: "Two-state toggle switch with sliding thumb.", category: "form" },
  { name: "radio-group", title: "Radio Group", description: "Accessible single-select radio button set.", category: "form" },
  { name: "slider", title: "Slider", description: "Draggable value slider with chunky thumb.", category: "form" },
  { name: "select", title: "Select", description: "Custom dashed listbox dropdown with keyboard navigation.", category: "form" },
  { name: "stepper", title: "Stepper", description: "Increment and decrement buttons with mono readout.", category: "form" },
  { name: "pin-input", title: "Pin Input", description: "Segmented single-character boxes for codes and OTP.", category: "form" },
  { name: "rating", title: "Rating", description: "Interactive star rating with live hover preview.", category: "form" },
  { name: "copy-button", title: "Copy Button", description: "Tactile button with clipboard feedback and check state.", category: "form" },
  { name: "search-bar", title: "Search Bar", description: "Dashed search field with shortcut keycap and clear action.", category: "form" },
  { name: "combobox", title: "Combobox", description: "Filterable searchable dropdown with instant keyboard filter.", category: "form" },
  { name: "file-dropzone", title: "File Dropzone", description: "Drag-and-drop upload zone with dashed borders and file preview.", category: "form" },
  { name: "color-picker", title: "Color Picker", description: "Palette swatch picker with framing and active mark.", category: "form" },
  { name: "password-strength", title: "Password Strength", description: "Segmented security verification meter with animated strength bars and criteria checklist.", category: "form" },
  { name: "inline-edit", title: "Inline Edit", description: "Click-to-edit field with focus outline, animated save pulse, and cancel action.", category: "form" },
  { name: "time-input", title: "Time Input", description: "Curtain call showtime selector with hours, minutes, and AM/PM stepper.", category: "form" },
  { name: "masked-input", title: "Masked Input", description: "Formatted code field with auto-formatted delimiters and validation mark.", category: "form" },
  { name: "date-picker", title: "Date Picker", description: "Date picker input with popover calendar and quick date selection.", category: "form" },
  { name: "dual-slider", title: "Dual Slider", description: "Price range selector with minimum and maximum draggable handles.", category: "form" },
  { name: "mention-input", title: "Mention Input", description: "Mention input with instant @ autocomplete popover.", category: "form" },
  { name: "autocomplete", title: "Autocomplete", description: "Typeahead search input with instant suggestions and keyboard select.", category: "form" },
  { name: "transfer-list", title: "Transfer List", description: "Two-column transfer list between available and claimed items.", category: "form" },
  { name: "tree-select", title: "Tree Select", description: "Hierarchical seating dropdown selector with expandable zone nodes.", category: "form" },
  { name: "masked-currency", title: "Masked Currency", description: "Formatted currency price input with prefix badge and numeric mask.", category: "form" },
  { name: "segmented-switch", title: "Segmented Switch", description: "Mechanical multi-option lever switch with smooth slide carriage.", category: "form" },
  { name: "theme-toggle", title: "Theme Toggle", description: "Theme switcher with day and night flip animation.", category: "form" },
  { name: "signature-pad", title: "Signature Pad", description: "Interactive canvas endorsement pad with clear action and receipt stamp.", category: "form" },
  { name: "seat-map", title: "Seat Map", description: "Interactive arena seating chart matrix grid with row letters, seat numbers, tier types, and price calculator.", category: "form" },
  { name: "keypad", title: "Keypad", description: "Numeric PIN keypad with tactile mechanical keys, visual pulse, and masked PIN display.", category: "form" },
  { name: "tag-input", title: "Tag Input", description: "Tag input with pill chip badges, remove buttons, backspace deletion, and dashed container.", category: "form" },

  // Display (27)
  { name: "ticket-card", title: "Ticket Card", description: "Complete admission ticket with notched edges and seat details.", category: "display" },
  { name: "coupon", title: "Coupon", description: "Discount coupon with scissor cutout lines and promo code copy.", category: "display" },
  { name: "boarding-pass", title: "Boarding Pass", description: "Flight pass with origin, destination and receipt section.", category: "display" },
  { name: "price-tag", title: "Price Tag", description: "Price tag with eyelet string hole and sale mark.", category: "display" },
  { name: "luggage-tag", title: "Luggage Tag", description: "Baggage claim tag with handle loop and destination code.", category: "display" },
  { name: "barcode", title: "Barcode", description: "Dynamic SVG barcode with mono serial readout.", category: "display" },
  { name: "stamp-seal", title: "Stamp Seal", description: "Rotated rubber stamp badge with double dashed circular ring.", category: "display" },
  { name: "card", title: "Card", description: "Double-frame surface container with header, content, and footer.", category: "display" },
  { name: "badge", title: "Badge", description: "Micro status pill with subtle entrance transition.", category: "display" },
  { name: "avatar", title: "Avatar", description: "Initials or photo badge with dashed ring.", category: "display" },
  { name: "progress", title: "Progress", description: "Marching striped progress indicator bar.", category: "display" },
  { name: "kbd", title: "Kbd", description: "Keycap indicator with raised bottom border for shortcuts.", category: "display" },
  { name: "star", title: "Star", description: "Current-color star glyph for ratings and counts.", category: "display" },
  { name: "separator", title: "Separator", description: "Horizontal or vertical dashed divider.", category: "display" },
  { name: "table", title: "Table", description: "Data table with dashed row dividers and mono headers.", category: "display" },
  { name: "marquee", title: "Marquee", description: "Smooth ticker reel that pauses on hover.", category: "display" },
  { name: "timeline", title: "Timeline", description: "Vertical chronological events with dashed connection stem.", category: "display" },
  { name: "sparkline", title: "Sparkline", description: "Lightweight SVG trend sparkline with animated end-point.", category: "display" },
  { name: "bar-chart", title: "Bar Chart", description: "Mini data bar chart with dashed guideline grids and hover zoom.", category: "display" },
  { name: "calendar", title: "Calendar", description: "Month calendar with date selection, month navigation, and today indicator.", category: "display" },
  { name: "data-table", title: "Data Table", description: "Sortable, searchable data table with row selection and pagination.", category: "display" },
  { name: "video-frame", title: "Video Frame", description: "Cinema screening container with sprocket edges and play overlay.", category: "display" },
  { name: "audio-mini", title: "Audio Mini", description: "Compact audio player with animated equalizer bars and duration counter.", category: "display" },
  { name: "section-heading", title: "Section Heading", description: "Theater and arena section divider banner with dashed rules and zone badges.", category: "display" },
  { name: "lightbox", title: "Lightbox", description: "Fullscreen media viewer with film frame edges and image paging.", category: "display" },
  { name: "sticky-bar", title: "Sticky Bar", description: "Floating bottom checkout bar with item counter and admission button.", category: "display" },
  { name: "stack", title: "Stack", description: "Stacked container with staggered angles and hover fan-out.", category: "display" },
  { name: "container", title: "Container", description: "Centered layout wrapper with notch cutouts.", category: "display" },
  { name: "kanban-lite", title: "Kanban Lite", description: "Queue and stage progression board with notch cards.", category: "display" },
  { name: "gantt-lite", title: "Gantt Lite", description: "Interactive festival and stage timetable schedule with animated now indicator.", category: "display" },
  { name: "stopwatch", title: "Stopwatch", description: "Precision timer with lap tear-offs and digital readout.", category: "display" },
  { name: "countup", title: "Countup", description: "Mechanical turnstile odometer counter with animated tally and slot frames.", category: "display" },
  { name: "nfc-badge", title: "NFC Badge", description: "Contactless gate pass tap simulator with animated radio wave ripple pulse, status badge, lanyard notch, and admission chime.", category: "display" },
  { name: "scratch-off", title: "Scratch Off", description: "Lottery ticket with interactive foil scratch layer and auto-reveal.", category: "display" },
  { name: "qr-reader", title: "QR Reader", description: "Turnstile simulated camera QR and barcode scanner viewfinder with animated laser sweep and targeting reticle.", category: "display" },
  { name: "audio-waveform", title: "Audio Waveform", description: "Interactive multi-bar audio wave visualizer for concert recordings with live animated frequency bars and timestamp readout.", category: "display" },
  { name: "ticket-fold", title: "Ticket Fold", description: "3D accordion fold pass that unfolds with smooth perspective rotation and tear-away slip.", category: "display" },
  { name: "split-flap", title: "Split Flap", description: "Mechanical departure board with flipping characters and retro terminal styling.", category: "display" },
  { name: "watermark", title: "Watermark", description: "Repeating watermark pattern with security angle.", category: "display" },
  { name: "turnstile-gate", title: "Turnstile Gate", description: "Mechanical rotor barrier with pass counter, status LED, and push animation.", category: "display" },
  { name: "collapsible", title: "Collapsible", description: "Standalone expandable disclosure card with notch header, animated height reveal and status mark.", category: "display" },
  { name: "aspect-ratio", title: "Aspect Ratio", description: "Proportional media container with preset ratios, framed border, and corner guides.", category: "display" },
  { name: "resizable", title: "Resizable", description: "Splitter layout panels with draggable resize handle, min/max limits and collapse button.", category: "display" },
  { name: "scroll-area", title: "Scroll Area", description: "Custom styled scrollable container with customized dashed scrollbar track, thumb indicator, horizontal/vertical support, and perforated top/bottom shadow fades.", category: "display" },
  { name: "pricing-table", title: "Pricing Table", description: "3-tier matrix with billing switcher, highlighted plan and feature checklist.", category: "display" },
  { name: "metric-card", title: "Metric Card", description: "Dashboard KPI card with value, trend delta and period label.", category: "display" },
  { name: "code-block", title: "Code Block", description: "Code snippet block with filename tab, language badge and copy button.", category: "display" },
  { name: "activity-feed", title: "Activity Feed", description: "Universal user and team activity stream for deployments, invites, edits, and security audits with timeline avatars, action badges, relative timestamps, and event icons.", category: "display" },
  { name: "credit-card", title: "Credit Card", description: "Universal payment card visualizer with real-time card number formatting, brand badge detection (Visa, Mastercard, Amex), metallic EMV chip, and interactive 3D flip card to show CVV.", category: "display" },
  { name: "file-upload-list", title: "File Upload List", description: "Multi-file upload manager queue with individual file progress percentage bars, file size formatting (KB/MB), file type badges, cancel/retry/remove buttons, and overall upload count status.", category: "feedback" },



  // Feedback (12)
  { name: "alert", title: "Alert", description: "Notice box with tone bar and status eyebrow.", category: "feedback" },
  { name: "tooltip", title: "Tooltip", description: "Floating helper tooltip on hover and keyboard focus.", category: "feedback" },
  { name: "dialog", title: "Dialog", description: "Accessible modal dialog with focus trap and scale animation.", category: "feedback" },
  { name: "toast", title: "Toast", description: "Transient stacked notices with auto-dismiss.", category: "feedback" },
  { name: "sheet", title: "Sheet", description: "Slide-over drawer panel with focus trap and scroll lock.", category: "feedback" },
  { name: "popover", title: "Popover", description: "Floating content panel anchored to an interactive trigger.", category: "feedback" },
  { name: "empty", title: "Empty", description: "Perforated placeholder box for zero-state views.", category: "feedback" },
  { name: "spinner", title: "Spinner", description: "Rotary loading indicator with dashed track and stamp accent.", category: "feedback" },
  { name: "skeleton", title: "Skeleton", description: "Dashed placeholder box with gentle pulse animation.", category: "feedback" },
  { name: "cookie-banner", title: "Cookie Banner", description: "Fixed privacy consent banner with accept and decline actions.", category: "feedback" },
  { name: "confetti-burst", title: "Confetti Burst", description: "CSS celebration burst with stamp-colored pieces flying outward.", category: "feedback" },
  { name: "tour", title: "Tour", description: "Interactive step-by-step guided onboarding card with progress indicators.", category: "feedback" },
  { name: "hover-card", title: "Hover Card", description: "Popover preview on hover and focus with configurable delays and alignment.", category: "feedback" },
  { name: "drawer", title: "Drawer", description: "Bottom slide-up drawer with pull handle, backdrop blur, and focus trap.", category: "feedback" },
  { name: "announcement-bar", title: "Announcement Bar", description: "Festival alert and headline announcement ribbon bar with perforated top/bottom tear lines, countdown urgency badge, action CTA button, and dismiss action.", category: "feedback" },
  { name: "status-dot", title: "Status Dot", description: "Live status beacon with radar sweep pulse, glow rings and occupancy levels.", category: "display" },
  { name: "donut-chart", title: "Donut Chart", description: "Interactive SVG donut and pie chart with segment hover highlight, tooltips, center total readout, and custom color legend.", category: "display" },

  // Navigation (17)
  { name: "tabs", title: "Tabs", description: "Segmented panel switch with roving keyboard focus.", category: "navigation" },
  { name: "accordion", title: "Accordion", description: "Collapsible disclosure items with smooth height transitions.", category: "navigation" },
  { name: "pagination", title: "Pagination", description: "Numbered buttons with ellipsis and page stepping.", category: "navigation" },
  { name: "breadcrumb", title: "Breadcrumb", description: "Hierarchical trail with slash separators.", category: "navigation" },
  { name: "steps", title: "Steps", description: "Data-driven wizard progression with numbered stamps.", category: "navigation" },
  { name: "toggle-group", title: "Toggle Group", description: "Single-choice segmented control with roving tabindex.", category: "navigation" },
  { name: "dropdown-menu", title: "Dropdown Menu", description: "Popup actions menu with keyboard shortcuts and items.", category: "navigation" },
  { name: "countdown", title: "Countdown", description: "Live ticking event timer with segmented cards.", category: "navigation" },
  { name: "command-palette", title: "Command Palette", description: "Modal search command palette with keyboard shortcuts, categorization, and filter.", category: "navigation" },
  { name: "context-menu", title: "Context Menu", description: "Right-click menu with smooth reveal, shortcuts, and dashed divider.", category: "navigation" },
  { name: "scroll-top", title: "Scroll Top", description: "Floating elevator button that scrolls smoothly to page top.", category: "navigation" },
  { name: "menubar", title: "Menubar", description: "Theater box office menu bar with dropdown menus, shortcuts, and dashed frames.", category: "navigation" },
  { name: "navbar", title: "Navbar", description: "Navigation bar with brand monogram and active links.", category: "navigation" },
  { name: "tree-nav", title: "Tree Nav", description: "Hierarchical explorer with collapsible nodes and icons.", category: "navigation" },
  { name: "sidebar", title: "Sidebar", description: "Collapsible navigation sidebar drawer with notch cutouts.", category: "navigation" },
  { name: "breadcrumb-dropdown", title: "Breadcrumb Dropdown", description: "Hierarchical route breadcrumb with popover dropdown for intermediate tiers.", category: "navigation" },
  { name: "dock", title: "Dock", description: "Floating application dock bar with hover magnification and active indicators.", category: "navigation" },
];

