export type ComponentCategory = "form" | "display" | "feedback" | "navigation";

export type ComponentMeta = {
  name: string;
  title: string;
  description: string;
  category: ComponentCategory;
  isNew?: boolean;
};

export const categories: { id: ComponentCategory; name: string; description: string }[] = [
  { id: "form", name: "Form", description: "Inputs, pickers, toggles and tactile controls." },
  { id: "display", name: "Display", description: "Surfaces, badges and data frames." },
  { id: "feedback", name: "Feedback", description: "Overlays, notices, sheets and loading states." },
  { id: "navigation", name: "Navigation", description: "Tabs, steps, breadcrumbs, menus and timers." },
];

export const components: ComponentMeta[] = [
  // Form (14)
  { name: "button", title: "Button", description: "Animated button with hover feedback and crisp focus.", category: "form" },
  { name: "input", title: "Input", description: "Text input with dashed focus border and design tokens.", category: "form" },
  { name: "textarea", title: "Textarea", description: "Multi-line text area matching Input styling.", category: "form" },
  { name: "checkbox", title: "Checkbox", description: "Crisp checkbox with bold checked states.", category: "form" },
  { name: "switch", title: "Switch", description: "Two-state toggle switch with sliding thumb.", category: "form" },
  { name: "radio-group", title: "Radio Group", description: "Accessible single-select radio button set.", category: "form" },
  { name: "slider", title: "Slider", description: "Draggable value slider with chunky thumb.", category: "form" },
  { name: "select", title: "Select", description: "Custom dashed listbox dropdown with keyboard navigation.", category: "form" },
  { name: "stepper", title: "Stepper", description: "Increment and decrement buttons with mono readout.", category: "form" },
  { name: "pin-input", title: "Pin Input", description: "Segmented single-character boxes for codes and OTP.", category: "form" },
  { name: "rating", title: "Rating", description: "Interactive star rating with live hover preview.", category: "form" },
  { name: "copy-button", title: "Copy Button", description: "Tactile button with clipboard feedback and check state.", category: "form" },
  { name: "search-bar", title: "Search Bar", description: "Dashed search field with shortcut keycap and clear action.", category: "form" },
  { name: "combobox", title: "Combobox", description: "Filterable searchable dropdown with instant keyboard filter.", category: "form" },
  { name: "file-dropzone", title: "File Dropzone", description: "Drag-and-drop upload zone with dashed borders and file preview.", category: "form" },
  { name: "color-picker", title: "Color Picker", description: "Palette swatch picker with framing and active mark.", category: "form" },
  { name: "password-strength", title: "Password Strength", description: "Segmented security verification meter with animated strength bars and criteria checklist.", category: "form" },
  { name: "inline-edit", title: "Inline Edit", description: "Click-to-edit field with focus outline, animated save pulse, and cancel action.", category: "form" },
  { name: "time-input", title: "Time Input", description: "Curtain call showtime selector with hours, minutes, and AM/PM stepper.", category: "form" },
  { name: "masked-input", title: "Masked Input", description: "Formatted code field with auto-formatted delimiters and validation mark.", category: "form" },
  { name: "date-picker", title: "Date Picker", description: "Date picker input with popover calendar and quick date selection.", category: "form" },
  { name: "dual-slider", title: "Dual Slider", description: "Price range selector with minimum and maximum draggable handles.", category: "form" },
  { name: "mention-input", title: "Mention Input", description: "Mention input with instant @ autocomplete popover.", category: "form" },
  { name: "autocomplete", title: "Autocomplete", description: "Typeahead search input with instant suggestions and keyboard select.", category: "form" },
  { name: "transfer-list", title: "Transfer List", description: "Two-column transfer list between available and claimed items.", category: "form" },
  { name: "tree-select", title: "Tree Select", description: "Hierarchical seating dropdown selector with expandable zone nodes.", category: "form" },
  { name: "masked-currency", title: "Masked Currency", description: "Formatted currency price input with prefix badge and numeric mask.", category: "form" },
  { name: "segmented-switch", title: "Segmented Switch", description: "Mechanical multi-option lever switch with smooth slide carriage.", category: "form" },
  { name: "theme-toggle", title: "Theme Toggle", description: "Theme switcher with day and night flip animation.", category: "form" },
  { name: "signature-pad", title: "Signature Pad", description: "Interactive canvas endorsement pad with clear action and receipt stamp.", category: "form" },
  { name: "seat-map", title: "Seat Map", description: "Interactive arena seating chart matrix grid with row letters, seat numbers, tier types, and price calculator.", category: "form" },
  { name: "keypad", title: "Keypad", description: "Numeric PIN keypad with tactile mechanical keys, visual pulse, and masked PIN display.", category: "form" },
  { name: "tag-input", title: "Tag Input", description: "Tag input with pill chip badges, remove buttons, backspace deletion, and dashed container.", category: "form" },

  // Display (27)
  { name: "ticket-card", title: "Ticket Card", description: "Complete admission ticket with notched edges and seat details.", category: "display" },
  { name: "coupon", title: "Coupon", description: "Discount coupon with scissor cutout lines and promo code copy.", category: "display" },
  { name: "boarding-pass", title: "Boarding Pass", description: "Flight pass with origin, destination and receipt section.", category: "display" },
  { name: "price-tag", title: "Price Tag", description: "Price tag with eyelet string hole and sale mark.", category: "display" },
  { name: "luggage-tag", title: "Luggage Tag", description: "Baggage claim tag with handle loop and destination code.", category: "display" },
  { name: "barcode", title: "Barcode", description: "Dynamic SVG barcode with mono serial readout.", category: "display" },
  { name: "stamp-seal", title: "Stamp Seal", description: "Rotated rubber stamp badge with double dashed circular ring.", category: "display" },
  { name: "card", title: "Card", description: "Double-frame surface container with header, content, and footer.", category: "display" },
  { name: "badge", title: "Badge", description: "Micro status pill with subtle entrance transition.", category: "display" },
  { name: "avatar", title: "Avatar", description: "Initials or photo badge with dashed ring.", category: "display" },
  { name: "progress", title: "Progress", description: "Marching striped progress indicator bar.", category: "display" },
  { name: "kbd", title: "Kbd", description: "Keycap indicator with raised bottom border for shortcuts.", category: "display" },
  { name: "star", title: "Star", description: "Current-color star glyph for ratings and counts.", category: "display" },
  { name: "separator", title: "Separator", description: "Horizontal or vertical dashed divider.", category: "display" },
  { name: "table", title: "Table", description: "Data table with dashed row dividers and mono headers.", category: "display" },
  { name: "marquee", title: "Marquee", description: "Smooth ticker reel that pauses on hover.", category: "display" },
  { name: "timeline", title: "Timeline", description: "Vertical chronological events with dashed connection stem.", category: "display" },
  { name: "sparkline", title: "Sparkline", description: "Lightweight SVG trend sparkline with animated end-point.", category: "display" },
  { name: "bar-chart", title: "Bar Chart", description: "Mini data bar chart with dashed guideline grids and hover zoom.", category: "display" },
  { name: "calendar", title: "Calendar", description: "Month calendar with date selection, month navigation, and today indicator.", category: "display" },
  { name: "data-table", title: "Data Table", description: "Sortable, searchable data table with row selection and pagination.", category: "display" },
  { name: "video-frame", title: "Video Frame", description: "Cinema screening container with sprocket edges and play overlay.", category: "display" },
  { name: "audio-mini", title: "Audio Mini", description: "Compact audio player with animated equalizer bars and duration counter.", category: "display" },
  { name: "section-heading", title: "Section Heading", description: "Theater and arena section divider banner with dashed rules and zone badges.", category: "display" },
  { name: "lightbox", title: "Lightbox", description: "Fullscreen media viewer with film frame edges and image paging.", category: "display" },
  { name: "sticky-bar", title: "Sticky Bar", description: "Floating bottom checkout bar with item counter and admission button.", category: "display" },
  { name: "stack", title: "Stack", description: "Stacked container with staggered angles and hover fan-out.", category: "display" },
  { name: "container", title: "Container", description: "Centered layout wrapper with notch cutouts.", category: "display" },
  { name: "kanban-lite", title: "Kanban Lite", description: "Queue and stage progression board with notch cards.", category: "display" },
  { name: "gantt-lite", title: "Gantt Lite", description: "Interactive festival and stage timetable schedule with animated now indicator.", category: "display" },
  { name: "stopwatch", title: "Stopwatch", description: "Precision timer with lap tear-offs and digital readout.", category: "display" },
  { name: "countup", title: "Countup", description: "Mechanical turnstile odometer counter with animated tally and slot frames.", category: "display" },
  { name: "nfc-badge", title: "NFC Badge", description: "Contactless gate pass tap simulator with animated radio wave ripple pulse, status badge, lanyard notch, and admission chime.", category: "display" },
  { name: "scratch-off", title: "Scratch Off", description: "Lottery ticket with interactive foil scratch layer and auto-reveal.", category: "display" },
  { name: "qr-reader", title: "QR Reader", description: "Turnstile simulated camera QR and barcode scanner viewfinder with animated laser sweep and targeting reticle.", category: "display" },
  { name: "audio-waveform", title: "Audio Waveform", description: "Interactive multi-bar audio wave visualizer for concert recordings with live animated frequency bars and timestamp readout.", category: "display" },
  { name: "ticket-fold", title: "Ticket Fold", description: "3D accordion fold pass that unfolds with smooth perspective rotation and tear-away slip.", category: "display" },
  { name: "split-flap", title: "Split Flap", description: "Mechanical departure board with flipping characters and retro terminal styling.", category: "display" },
  { name: "watermark", title: "Watermark", description: "Repeating watermark pattern with security angle.", category: "display" },
  { name: "turnstile-gate", title: "Turnstile Gate", description: "Mechanical rotor barrier with pass counter, status LED, and push animation.", category: "display" },
  { name: "collapsible", title: "Collapsible", description: "Standalone expandable disclosure card with notch header, animated height reveal and status mark.", category: "display" },
  { name: "aspect-ratio", title: "Aspect Ratio", description: "Proportional media container with preset ratios, framed border, and corner guides.", category: "display" },
  { name: "resizable", title: "Resizable", description: "Splitter layout panels with draggable resize handle, min/max limits and collapse button.", category: "display" },
  { name: "scroll-area", title: "Scroll Area", description: "Custom styled scrollable container with customized dashed scrollbar track, thumb indicator, horizontal/vertical support, and perforated top/bottom shadow fades.", category: "display" },
  { name: "pricing-table", title: "Pricing Table", description: "3-tier matrix with billing switcher, highlighted plan and feature checklist.", category: "display" },
  { name: "metric-card", title: "Metric Card", description: "Dashboard KPI card with value, trend delta and period label.", category: "display" },
  { name: "code-block", title: "Code Block", description: "Code snippet block with filename tab, language badge and copy button.", category: "display" },
  { name: "activity-feed", title: "Activity Feed", description: "Universal user and team activity stream for deployments, invites, edits, and security audits with timeline avatars, action badges, relative timestamps, and event icons.", category: "display" },
  { name: "credit-card", title: "Credit Card", description: "Universal payment card visualizer with real-time card number formatting, brand badge detection (Visa, Mastercard, Amex), metallic EMV chip, and interactive 3D flip card to show CVV.", category: "display" },
  { name: "file-upload-list", title: "File Upload List", description: "Multi-file upload manager queue with individual file progress percentage bars, file size formatting (KB/MB), file type badges, cancel/retry/remove buttons, and overall upload count status.", category: "feedback" },



  // Feedback (12)
  { name: "alert", title: "Alert", description: "Notice box with tone bar and status eyebrow.", category: "feedback" },
  { name: "tooltip", title: "Tooltip", description: "Floating helper tooltip on hover and keyboard focus.", category: "feedback" },
  { name: "dialog", title: "Dialog", description: "Accessible modal dialog with focus trap and scale animation.", category: "feedback" },
  { name: "toast", title: "Toast", description: "Transient stacked notices with auto-dismiss.", category: "feedback" },
  { name: "sheet", title: "Sheet", description: "Slide-over drawer panel with focus trap and scroll lock.", category: "feedback" },
  { name: "popover", title: "Popover", description: "Floating content panel anchored to an interactive trigger.", category: "feedback" },
  { name: "empty", title: "Empty", description: "Perforated placeholder box for zero-state views.", category: "feedback" },
  { name: "spinner", title: "Spinner", description: "Rotary loading indicator with dashed track and stamp accent.", category: "feedback" },
  { name: "skeleton", title: "Skeleton", description: "Dashed placeholder box with gentle pulse animation.", category: "feedback" },
  { name: "cookie-banner", title: "Cookie Banner", description: "Fixed privacy consent banner with accept and decline actions.", category: "feedback" },
  { name: "confetti-burst", title: "Confetti Burst", description: "CSS celebration burst with stamp-colored pieces flying outward.", category: "feedback" },
  { name: "tour", title: "Tour", description: "Interactive step-by-step guided onboarding card with progress indicators.", category: "feedback" },
  { name: "hover-card", title: "Hover Card", description: "Popover preview on hover and focus with configurable delays and alignment.", category: "feedback" },
  { name: "drawer", title: "Drawer", description: "Bottom slide-up drawer with pull handle, backdrop blur, and focus trap.", category: "feedback" },
  { name: "announcement-bar", title: "Announcement Bar", description: "Festival alert and headline announcement ribbon bar with perforated top/bottom tear lines, countdown urgency badge, action CTA button, and dismiss action.", category: "feedback" },
  { name: "status-dot", title: "Status Dot", description: "Live status beacon with radar sweep pulse, glow rings and occupancy levels.", category: "display" },
  { name: "donut-chart", title: "Donut Chart", description: "Interactive SVG donut and pie chart with segment hover highlight, tooltips, center total readout, and custom color legend.", category: "display" },

  // Navigation (17)
  { name: "tabs", title: "Tabs", description: "Segmented panel switch with roving keyboard focus.", category: "navigation" },
  { name: "accordion", title: "Accordion", description: "Collapsible disclosure items with smooth height transitions.", category: "navigation" },
  { name: "pagination", title: "Pagination", description: "Numbered buttons with ellipsis and page stepping.", category: "navigation" },
  { name: "breadcrumb", title: "Breadcrumb", description: "Hierarchical trail with slash separators.", category: "navigation" },
  { name: "steps", title: "Steps", description: "Data-driven wizard progression with numbered stamps.", category: "navigation" },
  { name: "toggle-group", title: "Toggle Group", description: "Single-choice segmented control with roving tabindex.", category: "navigation" },
  { name: "dropdown-menu", title: "Dropdown Menu", description: "Popup actions menu with keyboard shortcuts and items.", category: "navigation" },
  { name: "countdown", title: "Countdown", description: "Live ticking event timer with segmented cards.", category: "navigation" },
  { name: "command-palette", title: "Command Palette", description: "Modal search command palette with keyboard shortcuts, categorization, and filter.", category: "navigation" },
  { name: "context-menu", title: "Context Menu", description: "Right-click menu with smooth reveal, shortcuts, and dashed divider.", category: "navigation" },
  { name: "scroll-top", title: "Scroll Top", description: "Floating elevator button that scrolls smoothly to page top.", category: "navigation" },
  { name: "menubar", title: "Menubar", description: "Theater box office menu bar with dropdown menus, shortcuts, and dashed frames.", category: "navigation" },
  { name: "navbar", title: "Navbar", description: "Navigation bar with brand monogram and active links.", category: "navigation" },
  { name: "tree-nav", title: "Tree Nav", description: "Hierarchical explorer with collapsible nodes and icons.", category: "navigation" },
  { name: "sidebar", title: "Sidebar", description: "Collapsible navigation sidebar drawer with notch cutouts.", category: "navigation" },
  { name: "breadcrumb-dropdown", title: "Breadcrumb Dropdown", description: "Hierarchical route breadcrumb with popover dropdown for intermediate tiers.", category: "navigation" },
  { name: "dock", title: "Dock", description: "Floating application dock bar with hover magnification and active indicators.", category: "navigation" },

  // Wave expansion entries
  { name: "skeleton-v2", title: "Skeleton V2", description: "Shimmer sweep skeleton with text-line and card composition presets.", category: "feedback" },
  { name: "alert-dialog", title: "Alert Dialog", description: "Confirm/cancel modal with destructive variant for irreversible actions, Escape/backdrop close, and animated content.", category: "feedback" },
  { name: "carousel", title: "Carousel", description: "Sliding track carousel with prev/next arrows, dot indicators, keyboard arrows, and optional autoplay.", category: "navigation" },
  { name: "label", title: "Label", description: "Form label with mono uppercase styling and an animated stamp-red asterisk when required.", category: "form" },
  { name: "form-field", title: "Form Field", description: "Field wrapper with label, control, description, and error message with a shake-in animation on error.", category: "form" },
  { name: "field", title: "Field", description: "Composable field primitives: Field, FieldLabel, FieldControl, FieldDescription, FieldError, FieldGroup, FieldSet.", category: "form" },
  { name: "toggle", title: "Toggle", description: "Two-state button with aria-pressed, springy press animation, and default/outline/accent variants.", category: "form" },
  { name: "navigation-menu", title: "Navigation Menu", description: "Horizontal nav bar whose items reveal an animated panel below with height/fade reveal and sliding indicator.", category: "navigation" },
  { name: "multi-select", title: "Multi Select", description: "Trigger + popover picker with search input, checkbox options, and animated removable selection chips.", category: "form" },
  { name: "avatar-group", title: "Avatar Group", description: "Overlapping avatar stack with +N overflow chip that fans out on hover.", category: "display" },
  { name: "divider-with-text", title: "Divider With Text", description: "Centered label over dashed separator lines with a line-grow scaleX animation on mount.", category: "display" },
  { name: "input-group", title: "Input Group", description: "Input with prefix icon slot, suffix slot, and inner action button; dashed focus ring and animated underline sweep.", category: "form" },
  { name: "button-group", title: "Button Group", description: "Joins buttons with rounded outer corners, internal separators, and sliding hover highlight.", category: "form" },
  { name: "item", title: "Item", description: "Generic row surface with leading media, title, description, and trailing actions; hover lift with accent bar slide-in.", category: "display" },
  { name: "loading-button", title: "Loading Button", description: "Button with loading spinner swap, width locking to avoid jumps, and a brief success check-mark stamp.", category: "form" },
  { name: "checkbox-group", title: "Checkbox Group", description: "Checkbox options with a select-all row (indeterminate state), animated check fills, and staggered entrance.", category: "form" },
  { name: "listbox", title: "Listbox", description: "Single/multi selectable list with keyboard navigation, ARIA roles, and check marks that slide in.", category: "form" },
  { name: "dropdown-menu-v2", title: "Dropdown Menu V2", description: "V2 dropdown menu: nested submenus, checkbox items, radio groups, separators, danger items, and shortcut kbd hints.", category: "navigation" },
  { name: "heading", title: "Heading", description: "Semantic heading with level-based scale, optional mono eyebrow and per-level entrance animation.", category: "display" },
  { name: "text", title: "Text", description: "Typographic paragraph primitive with default, muted, small, lead and mono variants.", category: "display" },
  { name: "list", title: "List", description: "List with dashed, numbered and icon variants plus staggered item entrances and List/ListItem composition.", category: "display" },
  { name: "quote", title: "Quote", description: "Blockquote with dashed left frame, stamp entrance and mono uppercase cite line.", category: "display" },
  { name: "figure", title: "Figure", description: "Framed media figure with double-frame surface and delayed figcaption fade-in.", category: "display" },
  { name: "description-list", title: "DescriptionList", description: "Term/description pairs with mono uppercase terms, muted descriptions and staggered row entrances.", category: "display" },
  { name: "page-header", title: "PageHeader", description: "Page title with stamp entrance, fading description, actions slot and optional mono eyebrow.", category: "display" },
  { name: "hero", title: "Hero", description: "Landing hero with accent highlight word, primary/secondary actions and bottom marquee strip.", category: "display" },
  { name: "footer", title: "Footer", description: "Site footer with brand monogram, staggered link columns and dashed-top bottom bar.", category: "navigation" },
  { name: "media-object", title: "MediaObject", description: "Horizontal media plus content row with title, description, meta chips and hover lift.", category: "display" },
  { name: "link-card", title: "LinkCard", description: "Whole-card link with sliding arrow, darkening border on hover and fade-up entrance.", category: "display" },
  { name: "logo-cloud", title: "LogoCloud", description: "Grid or marquee row of monogram logo tiles in dashed frames with hover reveal.", category: "display" },
  { name: "faq", title: "Faq", description: "Self-contained accordion Q&A with one-open behavior, grid-rows height reveal and rotating plus icon.", category: "navigation" },
  { name: "testimonial", title: "Testimonial", description: "Quote card with initials avatar, name, role and staggered star rating pop-in.", category: "display" },
  { name: "team-grid", title: "TeamGrid", description: "Grid of member cards with initials avatars, roles, optional links and staggered hover-lift entrances.", category: "display" },
  { name: "feature-grid", title: "FeatureGrid", description: "Feature tiles with icon slot, stamp-on-hover icons, darkening borders and staggered entrance.", category: "display" },
  { name: "cta-section", title: "CtaSection", description: "Double-frame call-to-action band with stamp-seal corner badge and stamping action button.", category: "display" },
  { name: "line-chart", title: "Line Chart", description: "Multi-series line chart with stroke-dasharray animation and hover tooltips", category: "display" },
  { name: "area-chart", title: "Area Chart", description: "Filled area chart with gradient fills and hover highlights", category: "display" },
  { name: "stacked-bar", title: "Stacked Bar Chart", description: "Horizontal stacked bars with segmented rows and legend chips", category: "display" },
  { name: "gauge", title: "Gauge", description: "Half-donut SVG gauge with needle animation and value readout", category: "display" },
  { name: "progress-circle", title: "Progress Circle", description: "Circular progress ring with stroke-dashoffset animation and center percentage", category: "display" },
  { name: "radar-chart", title: "Radar Chart", description: "Spider web chart with polygon axes and data polygon animation", category: "display" },
  { name: "heatmap", title: "Heatmap", description: "Grid of colored cells showing value intensities with diagonal stagger", category: "display" },
  { name: "calendar-heatmap", title: "Calendar Heatmap", description: "GitHub-style Git calendar heatmap grid", category: "display" },
  { name: "funnel-chart", title: "Funnel Chart", description: "Horizontal funnel stages showing conversion percentages between steps", category: "display" },
  { name: "scatter-plot", title: "Scatter Plot", description: "SVG scatter plot with dashed axes and hover enlargements", category: "display" },
  { name: "waterfall-chart", title: "Waterfall Chart", description: "Floating bars showing incremental changes with connecting guides", category: "display" },
  { name: "candlestick-chart", title: "Candlestick Chart", description: "OHLC candlestick chart for financial data visualization", category: "display" },
  { name: "leaderboard", title: "Leaderboard", description: "Ranked leaderboard with medal tiles for top 3 and count-up scores", category: "display" },
  { name: "scoreboard", title: "Scoreboard", description: "Two-team score card with rolling digit animation", category: "display" },
  { name: "json-viewer", title: "JSON Viewer", description: "Collapsible JSON tree with mono keys and color-typed values", category: "display" },
  { name: "diff-viewer", title: "Diff Viewer", description: "Unified diff viewer showing added/removed/context lines", category: "display" },
  { name: "terminal", title: "Terminal", description: "Fake terminal card with sequential line reveal and blinking cursor", category: "display" },
  { name: "log-viewer", title: "Log Viewer", description: "Scrolling log stream with level badges and filter chips", category: "display" },
  { name: "treemap-chart", title: "Treemap Chart", description: "Squarified treemap with recursive rectangles and staggered labels", category: "display" },
  { name: "confirm-dialog", title: "ConfirmDialog", description: "Self-contained confirm dialog with focus trap and stamp entrance for confirm button in destructive mode.", category: "feedback" },
  { name: "result", title: "Result", description: "Full-panel status screen with icon circle, title, description, and actions slot; confetti-ish subtle burst on success.", category: "feedback" },
  { name: "loading-dots", title: "LoadingDots", description: "Three dots bounce in sequence with keyframe animation; sizes sm/md/lg and tone prop.", category: "feedback" },
  { name: "loading-overlay", title: "LoadingOverlay", description: "Absolute/fixed veil with backdrop blur and spinner; fade in/out with opacity transition.", category: "feedback" },
  { name: "fab", title: "Fab", description: "Floating action button fixed in corner with hover growth, ripple press, and tooltip label on hover.", category: "navigation" },
  { name: "speed-dial", title: "SpeedDial", description: "FAB that fans out mini action buttons in an arc with staggered scale-in when open; Escape closes.", category: "navigation" },
  { name: "notification-center", title: "NotificationCenter", description: "Bell button with unread badge + dropdown panel with notification rows, mark-all-read, empty state.", category: "feedback" },
  { name: "spotlight", title: "Spotlight", description: "Full-viewport dim overlay with cutout hole positioned via target ref/bounding box; pulse ring around target; caption card.", category: "feedback" },
  { name: "coach-mark", title: "CoachMark", description: "Single floating tip bubble anchored to trigger children with arrow, title, body, dismiss; pop-in with springy scale.", category: "feedback" },
  { name: "image-compare", title: "ImageCompare", description: "Before/after slider with clip-path inset controlled by draggable divider; BEFORE/AFTER labels.", category: "display" },
  { name: "zoom-image", title: "ZoomImage", description: "Image with hover magnifier lens tracking cursor; framed double border.", category: "display" },
  { name: "infinite-scroll", title: "InfiniteScroll", description: "IntersectionObserver sentinel: when visible calls onLoadMore, shows animated loader row; wraps children.", category: "display" },
  { name: "load-more", title: "LoadMore", description: "Button row \"LOAD MORE\" with progress mono counter; on click reveals hidden children with stagger.", category: "display" },
  { name: "virtual-list", title: "VirtualList", description: "Windowed list for fixed-height rows: scrollTop math, visible slice renders, spacer divs; smooth scroll.", category: "display" },
  { name: "scroll-shadow", title: "ScrollShadow", description: "Wrapper with top/bottom shadow indicators that fade in only when scrollable in that direction; dashed scrollbar styling.", category: "display" },
  { name: "reveal", title: "Reveal", description: "IntersectionObserver: children animate in when entering viewport with fade-up/scale variants, delay prop, once re-trigger option.", category: "display" },
  { name: "product-card", title: "Product Card", description: "Product card with image slot, price, discount badge and wishlist heart.", category: "display" },
  { name: "user-card", title: "User Card", description: "Profile card with avatar, role, meta chips and action slot.", category: "display" },
  { name: "article-card", title: "Article Card", description: "Blog article card with category badge, excerpt and author meta.", category: "display" },
  { name: "event-card", title: "Event Card", description: "Event card with perforated date block, venue and time chips.", category: "display" },
  { name: "invoice", title: "Invoice", description: "Invoice layout with line items, tax breakdown and stamped total.", category: "display" },
  { name: "receipt", title: "Receipt", description: "Thermal receipt with zigzag tear edge, mono lines and barcode footer.", category: "display" },
  { name: "checkout-summary", title: "Checkout Summary", description: "Cart summary with quantity steppers, tax row and checkout CTA.", category: "display" },
  { name: "cart-drawer", title: "Cart Drawer", description: "Slide-over cart drawer with quantity controls and animated removal.", category: "feedback" },
  { name: "size-picker", title: "Size Picker", description: "Size chip picker with out-of-stock strikes and stock dots.", category: "form" },
  { name: "variant-picker", title: "Variant Picker", description: "Color swatch and size variant picker with animated selection.", category: "form" },
  { name: "wishlist-button", title: "Wishlist Button", description: "Heart wishlist button with pop fill and floating burst.", category: "form" },
  { name: "add-to-cart-button", title: "Add To Cart Button", description: "Add-to-cart button with flying dot arc and check stamp.", category: "form" },
  { name: "order-card", title: "Order Card", description: "Order status card with step dots and item summary.", category: "display" },
  { name: "stamp-card", title: "Stamp Card", description: "Loyalty punch card with stamped circles and reward row.", category: "display" },
  { name: "gift-card", title: "Gift Card", description: "Gift card with ribbon stripe, amount and balance bar.", category: "display" },
  { name: "id-card", title: "Id Card", description: "Employee ID card with hologram shine sweep and barcode.", category: "display" },
  { name: "rsvp-card", title: "Rsvp Card", description: "Invitation RSVP card with attending toggle and wax stamp.", category: "display" },
  { name: "chat-window", title: "ChatWindow", description: "Full chat panel with message list, input bar, and typing indicator slot.", category: "display" },
  { name: "chat-bubble", title: "ChatBubble", description: "Single message bubble with tail, status ticks, and hover press feedback.", category: "display" },
  { name: "typing-indicator", title: "TypingIndicator", description: "Three bouncing dots with user name label indicating who is typing.", category: "display" },
  { name: "comment-thread", title: "CommentThread", description: "Nested comments with avatars, collapse/reply actions, and dashed indent guides.", category: "display" },
  { name: "reaction-bar", title: "ReactionBar", description: "Emoji buttons with counts, active reaction pops, and hover tooltips.", category: "feedback" },
  { name: "like-button", title: "LikeButton", description: "Heart/thumb button that fills on click with burst particle animation and count increment.", category: "feedback" },
  { name: "share-menu", title: "ShareMenu", description: "Platform icon row (X, Facebook, LinkedIn, Link) with copy link feedback and stamp stamp.", category: "navigation" },
  { name: "story-viewer", title: "StoryViewer", description: "Circular story ring with progress animation, avatar names, and tap zones for prev/next.", category: "display" },
  { name: "post-card", title: "PostCard", description: "Social post with header, body, gradient media placeholder, and action row with like/comment/share counts.", category: "display" },
  { name: "follower-list", title: "FollowerList", description: "Rows with avatars, names, handles, and Follow buttons that morph between states.", category: "display" },
  { name: "voice-message", title: "VoiceMessage", description: "Chat audio bubble with play/pause button and animated waveform bars showing audio duration.", category: "display" },
  { name: "emoji-picker", title: "EmojiPicker", description: "Panel with category tabs (Smileys, Gestures, Hearts, Objects), search filter, and emoji grid with selection callback.", category: "form" },
  { name: "audio-player", title: "AudioPlayer", description: "Full deck audio player with play/pause morph button, seek bar, time readout, volume slider, and track info", category: "display" },
  { name: "video-player", title: "VideoPlayer", description: "Video frame with sprocket styling, hover fade-in controls, progress bar with scrub preview", category: "display" },
  { name: "playlist", title: "Playlist", description: "Track rows with equalizer bars for active track, title/artist, duration, and slide-in marker", category: "display" },
  { name: "volume-slider", title: "VolumeSlider", description: "Vertical or horizontal slider with fill animation, mute toggle, and ARIA roles", category: "form" },
  { name: "podcast-player", title: "PodcastPlayer", description: "Episode card with art slot, play button, speed selector chips, skip buttons, and chapter ticks", category: "display" },
  { name: "video-thumbnail", title: "VideoThumbnail", description: "Poster frame with duration badge, play overlay circle that scales on hover with ripple ring, and title strip", category: "display" },
  { name: "media-controls", title: "MediaControls", description: "Compact transport bar with prev/play/next/stop buttons, progress micro-bar, and time display", category: "display" },
  { name: "live-badge", title: "LiveBadge", description: "LIVE indicator with blinking dot, mono uppercase label, and optional viewer count that ticks", category: "display" },
  { name: "time-ago", title: "TimeAgo", description: "Relative time display showing '5 MIN AGO' with live re-render tick every 30s", category: "display" },
  { name: "live-clock", title: "LiveClock", description: "Digital clock showing HH:MM:SS with optional timezone and variant support", category: "display" },
  { name: "typewriter", title: "Typewriter", description: "Types text char-by-char with blinking block cursor, loops through phrases", category: "display" },
  { name: "highlight-text", title: "HighlightText", description: "Highlights query matches inside text with accent background and animated reveal", category: "display" },
  { name: "truncate", title: "Truncate", description: "Single/multi-line clamp with optional expand toggle (MORE/LESS)", category: "display" },
  { name: "text-diff", title: "TextDiff", description: "Word-level diff showing added/removed words with animation", category: "form" },
  { name: "currency-display", title: "CurrencyDisplay", description: "Formatted money with symbol, mono integer part, smaller muted decimals, optional count-up animation", category: "display" },
  { name: "copy-chip", title: "CopyChip", description: "Small mono chip that copies to clipboard with check morph and 'COPIED' feedback", category: "form" },
  { name: "receipt-printer", title: "ReceiptPrinter", description: "Thermal printer that feeds mono receipt lines out of a printer slot with a stepped paper animation.", category: "display" },
  { name: "queue-ticket", title: "QueueTicket", description: "Take-a-number queue ticket with a big tear-off number tab, NOW SERVING ring and queue stats.", category: "display" },
  { name: "now-serving", title: "NowServing", description: "Split-flap style NOW SERVING board whose digits flip on value change with a blinking chime dot.", category: "feedback" },
  { name: "passport", title: "Passport", description: "Double-frame passport cover with monogram, holder fields and staggered visa stamp marks.", category: "display" },
  { name: "wax-seal", title: "WaxSeal", description: "Circular wax blob with a pressed-in monogram entrance and an optional cracked break state.", category: "display" },
  { name: "envelope", title: "Envelope", description: "Envelope whose flap opens with a 3D rotateX and the letter inside rises, on hover or via an open prop.", category: "display" },
  { name: "airmail-letter", title: "AirmailLetter", description: "Airmail bordered letter with red/blue diagonal stripes, mono lines, a postmark corner and an unfold entrance.", category: "display" },
  { name: "postmark", title: "Postmark", description: "Circular postal cancellation stamp with wavy lines, city and date arcs that stamps in on mount.", category: "display" },
  { name: "cassette-tape", title: "CassetteTape", description: "Cassette with two spinning reels, shifting tape amounts and a handwritten-style label with play toggle.", category: "display" },
  { name: "vinyl-record", title: "VinylRecord", description: "Spinning vinyl with radial grooves, center label, a tonearm that slides in and a wobble on drop.", category: "display" },
  { name: "flip-clock", title: "FlipClock", description: "Mechanical split-flap HH:MM clock whose digit cards flip on change with a blinking colon.", category: "display" },
  { name: "neon-sign", title: "NeonSign", description: "Neon sign with layered glow text-shadow, flicker-in entrance and a subtle per-letter buzz.", category: "display" },
  { name: "marquee-bulbs", title: "MarqueeBulbs", description: "Marquee board framed by chase-blinking bulbs with scrolling center text.", category: "display" },
  { name: "backstage-pass", title: "BackstagePass", description: "Laminated ALL ACCESS pass with lanyard hole, rotated stripe strip, shine sweep on hover and fake barcode.", category: "display" },
  { name: "wristband", title: "Wristband", description: "Festival wristband with patterned repeating stripes, snap closure, serial and a subtle breathing animation.", category: "display" },
  { name: "lanyard", title: "Lanyard", description: "Strap with clip that sways gently from the top and holds an attached card slot for children.", category: "display" },
  { name: "drink-ticket", title: "DrinkTicket", description: "Perforated drink coupon with glyph, GOOD FOR ONE copy and a tear-off stub that rotates on hover.", category: "display" },
  { name: "raffle-ticket", title: "RaffleTicket", description: "Raffle ticket with a big number, matching stub number and a winning highlight that pulses and stamps.", category: "display" },
  { name: "slot-machine", title: "SlotMachine", description: "Three-reel slot machine with staggered spinning reels, a pulling lever and payline highlight on stop.", category: "display" },
  { name: "prize-wheel", title: "PrizeWheel", description: "SVG prize wheel of tinted segments that spins with eased deceleration and a flicking pointer flapper.", category: "display" },
  { name: "dice", title: "Dice", description: "Pair of 3D dice that tumble with rapid face swaps and settle with a bounce on roll.", category: "display" },
  { name: "coin-flip", title: "CoinFlip", description: "Coin that rotates on Y through multiple turns, decelerating to a heads or tails face with a stamped result badge.", category: "display" },
  { name: "playing-card", title: "PlayingCard", description: "Playing card with corner rank and suit, big center suit, diamond-pattern back and a 3D flip on click.", category: "display" },
  { name: "bingo-card", title: "BingoCard", description: "5x5 B-I-N-G-O card whose cells stamp in on toggle with a free center and line-complete sweep highlights.", category: "display" },
  { name: "jumbotron", title: "Jumbotron", description: "Oversized scoreboard with pixel-style mono type, scanline sweep and scoreboard slots for home and away.", category: "display" },
  { name: "fireworks", title: "Fireworks", description: "Rockets that rise and burst into radial particle rings, looping while active.", category: "display" },
  { name: "disco-ball", title: "DiscoBall", description: "Tiled mirror sphere that slowly rotates and projects dancing light dots around the room.", category: "display" },
  { name: "stage-lights", title: "StageLights", description: "Two to four gradient light cones that sweep alternately over a glowing stage floor ellipse.", category: "display" },
  { name: "ticket-booth", title: "TicketBooth", description: "Booth window with TICKETS marquee header, counter ledge, speaker grille dots and a CLOSED flip sign.", category: "display" },
  { name: "drive-in-screen", title: "DriveInScreen", description: "Outdoor cinema screen with projection flicker, a car silhouette row and an intermission countdown slot.", category: "display" },
  { name: "ticket-stub-v2", title: "TicketStubV2", description: "Rip-off event stub whose tear line detaches the stub with rotate-and-fall on tear, plus serial and barcode.", category: "display" },
  { name: "tabbar", title: "TabBar", description: "Fixed bottom navigation bar with sliding active indicator pill and badge support", category: "navigation" },
  { name: "pager-dots", title: "PagerDots", description: "Navigation page indicators with active dot that stretches and variant styles", category: "navigation" },
  { name: "toc", title: "Toc", description: "Table of contents with IntersectionObserver scroll-spy and dashed active underline", category: "display" },
  { name: "app-shell", title: "AppShell", description: "Page skeleton with top bar, collapsible sidebar, and main content area with built-in skip-link", category: "navigation" },
  { name: "skip-link", title: "SkipLink", description: "Accessibility skip-link that becomes visible on keyboard focus with translate animation", category: "navigation" },
  { name: "back-link", title: "BackLink", description: "Chevron button with label that slides on hover, with focus ring", category: "navigation" },
  { name: "flyout-menu", title: "FlyoutMenu", description: "Hover dropdown menu with scale-in origin-top panel and keyboard navigation", category: "navigation" },
  { name: "scroll-spy-nav", title: "ScrollSpyNav", description: "Horizontal sticky navigation with active pill that slides under the active section, smooth scroll with reduced-motion fallback", category: "navigation" },
  { name: "phone-input", title: "PhoneInput", description: "Phone number input with country code selector and formatted display", category: "form" },
  { name: "email-input", title: "EmailInput", description: "Email input with live validation and typo domain suggestions", category: "form" },
  { name: "date-range-picker", title: "DateRangePicker", description: "Two-month mini calendar grid for selecting start and end dates with nights count", category: "form" },
  { name: "month-picker", title: "MonthPicker", description: "12-month grid for selecting a month with year navigation", category: "form" },
  { name: "year-picker", title: "YearPicker", description: "Year grid with page navigation for selecting a year", category: "form" },
  { name: "time-range-picker", title: "TimeRangePicker", description: "Two time inputs with duration readout that animates on change", category: "form" },
  { name: "clock-picker", title: "ClockPicker", description: "Analog clock with draggable hands for time selection", category: "form" },
  { name: "hotkey-recorder", title: "HotkeyRecorder", description: "Record keyboard hotkey combinations with visual chip display", category: "form" },
  { name: "file-input", title: "FileInput", description: "Styled file input with drop chips and selection count animation", category: "form" },
  { name: "slider-ticks", title: "SliderTicks", description: "Slider with tick marks, labels, and snap-to-ticks functionality", category: "form" },
  { name: "qr-code", title: "QR Code", description: "Generates QR codes with Reed-Solomon error correction, mask evaluation, and finder patterns. Includes encodeQrMatrix helper.", category: "display" },
  { name: "rich-text-editor", title: "Rich Text Editor", description: "Minimal contentEditable editor with toolbar (bold, italic, underline, lists, links, quote, code) and word/char counter.", category: "form" },
  { name: "image-crop", title: "Image Crop", description: "Canvas-based image cropping with draggable crop rect, rule-of-thirds grid, resize handles, and dataURL output.", category: "display" },
  { name: "sankey-chart", title: "Sankey Chart", description: "Two-level flow diagram with bezier ribbons, value-based width, hover tooltips, and entrance animations.", category: "display" },
  { name: "org-chart", title: "Org Chart", description: "Hierarchical tree of boxes with connector lines, expand/collapse nodes, avatar initials, and entrance animations.", category: "display" },
  { name: "hooks", title: "Hooks", description: "SSR-safe React hooks: media query, localStorage, intersection, click-outside, copy, hotkey, and debounce.", category: "form" },
  { name: "focus-trap", title: "Focus Trap", description: "Pure TypeScript focus trapping helpers for accessible overlays: getFocusable and trapFocus.", category: "form" },
];